# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20160611_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='com_type',
            field=models.IntegerField(choices=[(0, '\u672a\u5206\u7c7b'), (1, '\u8ba2\u5355/\u914d\u9001'), (4, '\u552e\u540e\u95ee\u9898'), (2, '\u4ea7\u54c1\u5efa\u8bae'), (3, '\u5176\u4ed6\u95ee\u9898')], default=3, verbose_name='\u7c7b\u578b'),
        ),
    ]
