# coding:utf-8

ACTIVES=[
    {
     'id':1,
     'style':'model_1',
     'title':'常被人说比实际年龄',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-01.png',
     'choices':[('A',0),('B',5),('C',10)]
    },
    {'id':2,
     'style':'model_2',
     'title':'当你五十岁的时候，希望自己变成什么样子？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-02.png',
     'choices':[('A',10),('B',0)]
    },
    {'id':3,
     'style':'model_3',
     'title':'你购置服装，通常是怎样的情形？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-03.png',
     'choices':[('A',5),('B',0),('C',10)]
    },
    {'id':4,
     'style':'model_1',
     'title':'买衣服的的时候开始更佳关注衣服的面料是而不是款式？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-04.png',
     'choices':[('A',0),('B',10),('C',5)]
    },
    {'id':5,
     'style':'model_1',
     'title':'闺蜜聚会时你更喜欢穿？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-05.png',
     'choices':[('A',5),('B',0),('C',10)]
    },
    {'id':6,
     'style':'model_1',
     'title':'和自己的伴侣出去旅游的时候希望你们穿的是？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-06.png',
     'choices':[('A',0),('B',5),('C',10)]
    },
    {'id':7,
     'style':'model_1',
     'title':'你衣橱里面衣服的颜色比较多的是？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-07.png',
     'choices':[('A',5),('B',10),('C',0)]
    },
    {'id':8,
     'style':'model_1',
     'title':'你的发型是？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-08.png',
     'choices':[('A',0),('B',5),('C',10)]
    },
    {'id':9,
     'style':'model_3',
     'title':'你喜欢看老电影胜于喜欢看新上映的电影吗？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-09.png',
     'choices':[('A',0),('B',10),('C',5)]
    },
    {'id':10,
     'style':'model_1',
     'title':'你觉得自己性感成分多于漂亮成分吗？',
     'image':'http://7xogkj.com2.z0.glb.qiniucdn.com/dress_%E9%A2%98%E7%9B%AE-10.png',
     'choices':[('A',0),('B',10),('C',5)]
    }
]