# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_logisticscompany_express_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticscompany',
            name='kd100_express_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5feb\u9012100\u7f16\u7801'),
        ),
    ]
