# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_logisticscompany_kd100_express_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticscompany',
            name='type',
            field=models.IntegerField(db_index=True, default=0, help_text='\u53d1\u8d27\u7269\u6d41\u516c\u53f8\u4e0d\u4ec5\u7528\u4e8e\u6536\u8d27\u8fd8\u53ef\u7528\u4e8e\u53d1\u8d27', verbose_name='\u7269\u6d41\u516c\u53f8\u7528\u9014'),
        ),
    ]
