# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0005_add_field_total_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyskuamountstat',
            name='coin_payment',
            field=models.IntegerField(default=0, help_text='\u5c0f\u9e7f\u5e01\u53ea\u53ef\u7528\u4e8e\u4e70\u5238', verbose_name='\u652f\u4ed8\u5c0f\u9e7f\u5e01'),
        ),
        migrations.AddField(
            model_name='dailyskuamountstat',
            name='total_cost',
            field=models.IntegerField(default=0, help_text='\u6309\u5546\u54c1\u6700\u540e\u4e00\u6b21\u91c7\u8d2d\u4ef7\u8ba1\u7b97', verbose_name='\u5546\u54c1\u8fdb\u4ef7'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='total_boutique',
            field=models.IntegerField(default=0, help_text='\u5305\u542b\u5c0f\u9e7f\u5e01\u5145\u503c', verbose_name='\u8d2d\u5238&\u5145\u503c'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='total_coin',
            field=models.IntegerField(default=0, help_text='\u5c0f\u9e7f\u5e01\u652f\u4ed8', verbose_name='\u5e01\u652f\u4ed8\u989d'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='total_paycash',
            field=models.IntegerField(default=0, help_text='\u6240\u6709\u8ba2\u5355\u652f\u4ed8\u73b0\u91d1', verbose_name='\u5b9e\u4ed8\u73b0\u91d1'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='total_payment',
            field=models.IntegerField(default=0, help_text='\u6240\u6709\u8ba2\u5355\u603b\u91d1\u989d', verbose_name='\u65e5\u6210\u4ea4\u989d'),
        ),
    ]
