# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0006_refunds_add_ware_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='num_iid',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='\u5546\u54c1ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3'), (10, '\u8702\u5de2\u5341\u91cc\u6d0b\u573a')], default=None, null=True, verbose_name='\u9000\u8d27\u4ed3\u5e93'),
        ),
    ]
