# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0014_add_transcoupon_elitescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontransferrecord',
            name='transfer_type',
            field=models.IntegerField(choices=[(1, '\u9000\u5238\u6362\u94b1'), (2, '\u8f6c\u7ed9\u4e0b\u5c5e'), (3, '\u76f4\u63a5\u4e70\u8d27'), (4, '\u82b1\u94b1\u4e70\u5238'), (5, '\u4e0b\u5c5e\u9000\u5238'), (6, '\u9000\u8d27\u9000\u5238'), (7, '\u7cfb\u7edf\u8d60\u9001'), (8, '\u5151\u6362\u8ba2\u5355')], db_index=True, default=0, verbose_name='\u6d41\u901a\u7c7b\u578b'),
        ),
    ]
