# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0015_auto_20161203_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCouponDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('transfer_id', models.IntegerField(db_index=True, verbose_name='\u6d41\u901a\u8bb0\u5f55id')),
                ('transfer_type', models.IntegerField(choices=[(1, '\u9000\u5238\u6362\u94b1'), (2, '\u8f6c\u7ed9\u4e0b\u5c5e'), (3, '\u76f4\u63a5\u4e70\u8d27'), (4, '\u82b1\u94b1\u4e70\u5238'), (5, '\u4e0b\u5c5e\u9000\u5238'), (6, '\u9000\u8d27\u9000\u5238'), (7, '\u7cfb\u7edf\u8d60\u9001'), (8, '\u5151\u6362\u8ba2\u5355')], db_index=True, default=0, verbose_name='\u6d41\u901a\u7c7b\u578b')),
                ('coupon_id', models.BigIntegerField(db_index=True, verbose_name='\u4f18\u60e0\u5238id')),
            ],
            options={
                'db_table': 'flashsale_transfer_detail',
                'verbose_name': '\u7279\u5356/\u4f18\u60e0\u5238/\u6d41\u901a\u660e\u7ec6\u8868',
                'verbose_name_plural': '\u7279\u5356/\u4f18\u60e0\u5238/\u6d41\u901a\u660e\u7ec6\u5217\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transfercoupondetail',
            unique_together=set([('transfer_id', 'coupon_id')]),
        ),
    ]
