# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import flashsale.coupon.models.coupon_template


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0017_create_transfer_coupon_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontemplate',
            name='template_no',
            field=models.CharField(default=flashsale.coupon.models.coupon_template.default_coupon_template_no, max_length=64, unique=True, verbose_name='\u4f18\u60e0\u5238no'),
        ),
    ]
