# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_change_template_no_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='is_chained',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u53d1\u751f\u8f6c\u79fb'),
        ),
        migrations.AlterField(
            model_name='coupontemplate',
            name='scope_type',
            field=models.IntegerField(choices=[(1, '\u7279\u5356\u5546\u54c1\u901a\u7528'), (2, '\u7c7b\u76ee\u4e13\u7528'), (3, '\u5546\u54c1\u4e13\u7528')], default=1, verbose_name='\u4f7f\u7528\u8303\u56f4'),
        ),
    ]
