# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_add_field_is_chained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='is_chained',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u8f6c\u624b'),
        ),
    ]
