# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_add_field_transfercouponrecord'),
        ('coupon', '0020_auto_20170109_2033'),
    ]

    operations = [
    ]
