# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_add_field_transfer_3types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(1, '\u666e\u901a\u7c7b\u578b'), (5, '\u4e0b\u5355\u7ea2\u5305'), (2, '\u8ba2\u5355\u5206\u4eab'), (3, '\u63a8\u8350\u4e13\u4eab'), (4, '\u552e\u540e\u8865\u507f'), (6, '\u6d3b\u52a8\u5206\u4eab'), (7, '\u63d0\u73b0\u5151\u6362'), (8, '\u7cbe\u54c1\u4e13\u7528\u5238')], db_index=True, default=1, verbose_name='\u4f18\u60e0\u5238\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='is_chained',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u6d41\u901a'),
        ),
    ]
