# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_add_index_to_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='is_buyed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u652f\u4ed8\u8d2d\u4e70'),
        ),
    ]
