build:
  image: registry.aliyuncs.com/xiaolu-img/xiaolusys-base:78a9e53f221ca41896124f9fe438452cd483203a
  environment:
    - TARGET=staging
  commands:
    - mkdir -p /data/log/django
    - cd shopmanager;python manage.py migrate --noinput
    - python manage.py test -t . --keepdb
  when:
    branch: [staging,alpha]
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: latest
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: alpha
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys
    tag: django18
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    when:
      branch: django18
deploy:
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: admin
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest      
      - docker rm -f gunicorn 
      - docker run --name=gunicorn --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000 -e BLUEWARE_CONFIG_FILE=blueware.ini
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program gunicorn -k gevent -c taobao_gunicorn_conf.py shopmanager.wsgi
      - docker rm -f celery 
      - docker run --name=celery --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1 registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program celery worker -c 100 -A shopmanager --loglevel=ERROR
        -Q apis,default,peroid,async,notify,logistics,dinghuo
      - docker rm -f celery-flower
      - docker run --name=celery-flower --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:5555:5555 -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest celery flower -A shopmanager --loglevel=ERROR
      - docker rm -f celerybeat
      - docker run --name=celerybeat --restart=always -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        -d registry.aliyuncs.com/xiaolu-img/xiaolusys:latest python manage.py celery beat --loglevel=ERROR
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: alpha
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn-staging
      - docker run --name=gunicorn-staging --restart=always -e INSTANCE=mall -e TARGET=staging -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9001:9000 -e
        BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program gunicorn -k gevent -c staging_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host: staging.xiaolumm.com
    user: root
    when:
      branch: django18
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
      - docker rm -f gunicorn-django18
      - docker run --name=gunicorn-django18 --restart=always
        -e INSTANCE=mall -e TARGET=django18 -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9002:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:django18
        blueware-admin run-program gunicorn -k gevent -c staging_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host:
      - sale.xiaolumm.com
      - sale3.xiaolumm.com
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f gunicorn
      - docker run --name=gunicorn --restart=always
        -e INSTANCE=mall -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -d -p `ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`:9000:9000
        -e BLUEWARE_CONFIG_FILE=blueware.ini registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
        blueware-admin run-program gunicorn -k gevent -c taobao_gunicorn_conf.py shopmanager.wsgi
  ssh:
    host:
      - sale2.xiaolumm.com
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xiaolu-img/xiaolusys:latest
      - docker rm -f celery
      - docker run --name=celery --restart=always -d -e TARGET=production -e MYSQL_AUTH=$$MYSQL_AUTH -e REDIS_AUTH=$$REDIS_AUTH
        --volumes-from=static -e C_FORCE_ROOT=1 -e BLUEWARE_CONFIG_FILE=blueware.ini -e C_FORCE_ROOT=1
        registry.aliyuncs.com/xiaolu-img/xiaolusys:latest blueware-admin run-program
        celery multi start 4 -P gevent -c:1-4 500 -A shopmanager --loglevel=ERROR
        -Q notify,frency,mama,coupon,activevalue,mamafortune,relationship,carryrecord,skustats,statistics,logistics,carrytotal,integral
