# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0034_saleproductmanage_is_sale_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecategoryversion',
            name='sha1',
            field=models.CharField(blank=True, max_length=128, verbose_name='sha1\u503c'),
        ),
    ]
