# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0041_auto_20170308_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecategory',
            name='is_view',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u5c55\u793a\u7ed9\u7528\u6237'),
        ),
    ]
