# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0043_salesupplier_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('product_id', models.IntegerField(verbose_name='\u5546\u54c1id')),
                ('sale_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.SaleProduct')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u9009\u54c1\u5173\u7cfb',
                'verbose_name_plural': '\u5546\u54c1\u9009\u54c1\u5173\u8054\u5217\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='saleproductrelation',
            unique_together=set([('sale_product', 'product_id')]),
        ),
    ]
