# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-05 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitVIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('progress', models.CharField(blank=True, choices=[('none', '\u672a\u7533\u8bf7'), ('profile', '\u586b\u5199\u8d44\u6599'), ('pay', '\u652f\u4ed8\u62bc\u91d1'), ('pass', '\u7533\u8bf7\u6210\u529f')], db_index=True, default='none', max_length=8, verbose_name='\u7533\u8bf7\u8fdb\u5ea6')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitmall.BitVIP', verbose_name='\u9080\u8bf7\u4eba')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bit_vip', to=settings.AUTH_USER_MODEL, verbose_name='\u539f\u59cb\u7528\u6237')),
            ],
            options={
                'db_table': 'bitmall_vip',
                'verbose_name': '\u6bd4\u7279\u5546\u57ce\u7528\u6237',
                'verbose_name_plural': '\u6bd4\u7279\u5546\u57ce\u7528\u6237\u5217\u8868',
            },
        ),
    ]
