# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsmgr', '0003_auto_20161118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsactivity',
            name='sms_template_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5916\u90e8\u6a21\u677f\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='smsplatform',
            name='is_force_sign',
            field=models.BooleanField(default=False, verbose_name='\u5f3a\u5236\u7b7e\u540d'),
        ),
        migrations.AddField(
            model_name='smsplatform',
            name='sign_name',
            field=models.CharField(blank=True, max_length=16, verbose_name='\u7b7e\u540d\u5185\u5bb9'),
        ),
    ]
