# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsmgr', '0004_auto_20161119_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsactivity',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='smsplatform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsplatform',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='smsrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smsrecord',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65e5\u671f'),
            preserve_default=False,
        ),
    ]
