# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsmgr', '0005_auto_20161119_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsactivity',
            name='sms_type',
            field=models.CharField(choices=[('paycall', '\u4ed8\u6b3e\u63d0\u9192'), ('notify', '\u53d1\u8d27\u901a\u77e5'), ('s_delay', '\u5ef6\u8fdf\u53d1\u8d27\u901a\u77e5'), ('sign', '\u7b7e\u6536\u63d0\u9192'), ('birth', '\u751f\u65e5\u795d\u798f'), ('activity', '\u6d3b\u52a8\u5ba3\u4f20'), ('code', '\u9a8c\u8bc1\u7801'), ('later_send', '\u4e94\u5929\u672a\u53d1\u8d27'), ('goods_lack', '\u7f3a\u8d27\u901a\u77e5'), ('appupdate', 'APP\u66f4\u65b0'), ('lackrefund', '\u7f3a\u8d27\u9000\u6b3e\u901a\u77e5'), ('refund_deny', '\u62d2\u7edd\u9000\u6b3e\u7533\u8bf7\u901a\u77e5'), ('refund_approve', '\u540c\u610f\u9000\u6b3e\u8fd4\u6b3e\u901a\u77e5'), ('refund_return', '\u540c\u610f\u9000\u8d27\u7533\u8bf7\u901a\u77e5'), ('refund_ok', '\u9000\u8d27\u9000\u6b3e\u6210\u529f\u63d0\u9192'), ('ordercarry', '\u5988\u5988\u8ba2\u5355\u6536\u76ca\u901a\u77e5'), ('mama_renew', '\u5988\u5988\u7eed\u8d39\u63d0\u9192'), ('sbweixin', '\u63d0\u9192\u5988\u5988\u5173\u6ce8\u5fae\u4fe1'), ('tocity', '\u540c\u57ce\u63d0\u9192')], max_length=16, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='smsrecord',
            name='task_type',
            field=models.CharField(choices=[('paycall', '\u4ed8\u6b3e\u63d0\u9192'), ('notify', '\u53d1\u8d27\u901a\u77e5'), ('s_delay', '\u5ef6\u8fdf\u53d1\u8d27\u901a\u77e5'), ('sign', '\u7b7e\u6536\u63d0\u9192'), ('birth', '\u751f\u65e5\u795d\u798f'), ('activity', '\u6d3b\u52a8\u5ba3\u4f20'), ('code', '\u9a8c\u8bc1\u7801'), ('later_send', '\u4e94\u5929\u672a\u53d1\u8d27'), ('goods_lack', '\u7f3a\u8d27\u901a\u77e5'), ('appupdate', 'APP\u66f4\u65b0'), ('lackrefund', '\u7f3a\u8d27\u9000\u6b3e\u901a\u77e5'), ('refund_deny', '\u62d2\u7edd\u9000\u6b3e\u7533\u8bf7\u901a\u77e5'), ('refund_approve', '\u540c\u610f\u9000\u6b3e\u8fd4\u6b3e\u901a\u77e5'), ('refund_return', '\u540c\u610f\u9000\u8d27\u7533\u8bf7\u901a\u77e5'), ('refund_ok', '\u9000\u8d27\u9000\u6b3e\u6210\u529f\u63d0\u9192'), ('ordercarry', '\u5988\u5988\u8ba2\u5355\u6536\u76ca\u901a\u77e5'), ('mama_renew', '\u5988\u5988\u7eed\u8d39\u63d0\u9192'), ('sbweixin', '\u63d0\u9192\u5988\u5988\u5173\u6ce8\u5fae\u4fe1'), ('tocity', '\u540c\u57ce\u63d0\u9192')], db_index=True, max_length=10, verbose_name='\u7c7b\u578b'),
        ),
    ]
