# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinRedEnvelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('mch_billno', models.CharField(max_length=28, unique=True, verbose_name='\u5546\u6237\u8ba2\u5355\u53f7')),
                ('mch_id', models.CharField(max_length=32, verbose_name='\u5546\u6237\u53f7')),
                ('wxappid', models.CharField(max_length=32, verbose_name='\u516c\u4f17\u53f7appid')),
                ('send_name', models.CharField(max_length=32, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('openid', models.CharField(db_index=True, max_length=32, verbose_name='\u63a5\u6536\u8005openid')),
                ('total_amount', models.IntegerField(default=0, verbose_name='\u7ea2\u5305\u91d1\u989d(\u5206)')),
                ('total_num', models.IntegerField(default=1, verbose_name='\u7ea2\u5305\u53d1\u653e\u4eba\u6570')),
                ('wishing', models.CharField(max_length=128, verbose_name='\u7ea2\u5305\u795d\u798f\u8bed')),
                ('client_ip', models.CharField(max_length=15, verbose_name='\u8c03\u7528\u63a5\u53e3\u7684IP')),
                ('act_name', models.CharField(max_length=32, verbose_name='\u6d3b\u52a8\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8')),
                ('send_listid', models.CharField(blank=True, max_length=32, verbose_name='\u7ea2\u5305\u8ba2\u5355\u7684\u5fae\u4fe1\u5355\u53f7')),
                ('return_code', models.CharField(max_length=16, verbose_name='\u8fd4\u56de\u72b6\u6001\u7801')),
                ('return_msg', models.CharField(blank=True, max_length=128, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('result_code', models.CharField(max_length=16, verbose_name='\u4e1a\u52a1\u7ed3\u679c')),
                ('err_code', models.CharField(blank=True, max_length=32, verbose_name='\u9519\u8bef\u4ee3\u7801')),
                ('err_code_des', models.CharField(blank=True, max_length=128, verbose_name='\u9519\u8bef\u4ee3\u7801\u63cf\u8ff0')),
                ('status', models.CharField(choices=[(b'unsend', '\u5f85\u53d1\u653e'), (b'sending', '\u53d1\u653e\u4e2d'), (b'sent', '\u5df2\u53d1\u653e\u5f85\u9886\u53d6'), (b'failed', '\u53d1\u653e\u5931\u8d25'), (b'received', '\u5df2\u9886\u53d6'), (b'rfund_ing', '\u9000\u6b3e\u4e2d'), (b'refund', '\u5df2\u9000\u6b3e')], default=b'unsend', max_length=16, verbose_name='\u53d1\u9001\u72b6\u6001')),
                ('send_time', models.DateTimeField(null=True, verbose_name='\u7ea2\u5305\u53d1\u9001\u65f6\u95f4')),
                ('refund_time', models.DateTimeField(null=True, verbose_name='\u7ea2\u5305\u9000\u6b3e\u65f6\u95f4')),
                ('rcv_time', models.DateTimeField(null=True, verbose_name='\u7ea2\u5305\u9886\u53d6\u65f6\u95f4')),
            ],
            options={
                'db_table': 'xiaolupay_weixin_red_envelope',
            },
        ),
    ]
