# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0001_create_table_xiaolupay_weixin_red_envelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='\u5546\u5bb6\u8ba2\u5355\u53f7')),
                ('channel', models.CharField(choices=[('wx', '\u5fae\u4fe1\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9d\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053')),
                ('livemode', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u8ba2\u5355')),
                ('paid', models.BooleanField(default=False, verbose_name='\u5df2\u652f\u4ed8')),
                ('refunded', models.BooleanField(default=False, verbose_name='\u5df2\u9000\u6b3e')),
                ('client_ip', models.CharField(max_length=24, verbose_name='\u5ba2\u6237\u7aefIP')),
                ('amount', models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u91d1\u989d(\u5206)')),
                ('currency', models.CharField(choices=[('cny', '\u4eba\u6c11\u5e01')], default='cny', max_length=16, verbose_name='\u5e01\u79cd')),
                ('subject', models.CharField(blank=True, max_length=64, verbose_name='\u6807\u9898')),
                ('body', models.CharField(blank=True, max_length=256, verbose_name='\u8be6\u60c5')),
                ('time_paid', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4')),
                ('time_expire', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u622a\u6b62\u4ed8\u6b3e\u65f6\u95f4')),
                ('transaction_no', models.CharField(blank=True, max_length=64, verbose_name='\u4e8b\u52a1no')),
                ('amount_refunded', models.IntegerField(default=0, verbose_name='\u9000\u6b3e\u91d1\u989d(\u5206)')),
                ('failure_code', models.CharField(blank=True, max_length=32, verbose_name='\u9519\u8bef\u7f16\u7801')),
                ('failure_msg', models.CharField(blank=True, max_length=32, verbose_name='\u9519\u8bef\u7f16\u7801')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='\u5907\u6ce8')),
                ('extra', jsonfield.fields.JSONField(default={}, max_length=512, verbose_name='\u9644\u52a0\u53c2\u6570')),
            ],
            options={
                'db_table': 'xiaolupay_charge',
                'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u652f\u4ed8\u8bb0\u5f55',
                'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u652f\u4ed8\u8bb0\u5f55\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('order_no', models.CharField(max_length=64, verbose_name='\u5546\u5bb6\u8ba2\u5355\u53f7')),
                ('channel', models.CharField(choices=[('wx', '\u5fae\u4fe1\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9d\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053')),
                ('extra', jsonfield.fields.JSONField(default={}, max_length=1024, verbose_name='\u6e20\u9053\u51ed\u8bc1')),
            ],
            options={
                'db_table': 'xiaolupay_credential',
                'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u51ed\u8bc1',
                'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u51ed\u8bc1\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='weixinredenvelope',
            name='status',
            field=models.CharField(choices=[(b'UNSEND', '\u5f85\u53d1\u653e'), (b'SENDING', '\u53d1\u653e\u4e2d'), (b'SENT', '\u5df2\u53d1\u653e\u5f85\u9886\u53d6'), (b'FAILED', '\u53d1\u653e\u5931\u8d25'), (b'RECEIVED', '\u5df2\u9886\u53d6'), (b'RFUND_ING', '\u9000\u6b3e\u4e2d'), (b'REFUND', '\u5df2\u9000\u6b3e')], default=b'UNSEND', max_length=16, verbose_name='\u53d1\u9001\u72b6\u6001'),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together=set([('order_no', 'channel')]),
        ),
    ]
