# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0002_auto_20161128_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('refund_no', models.CharField(max_length=64, unique=True, verbose_name='\u5546\u5bb6\u9000\u6b3e\u7f16\u53f7')),
                ('amount', models.IntegerField(default=0, verbose_name='\u9000\u6b3e\u91d1\u989d(\u5206)')),
                ('succeed', models.BooleanField(default=False, verbose_name='\u9000\u6b3e\u6210\u529f')),
                ('status', models.CharField(choices=[('pending', '\u5904\u7406\u4e2d'), ('succeeded', '\u6210\u529f'), ('failed', '\u5931\u8d25')], default='pending', max_length=16, verbose_name='\u9000\u6b3e\u72b6\u6001')),
                ('time_succeed', models.DateTimeField(blank=True, null=True, verbose_name='\u9000\u6b3e\u6210\u529f\u65f6\u95f4')),
                ('description', models.CharField(max_length=256, verbose_name='\u9000\u6b3e\u8bf4\u660e')),
                ('failure_code', models.CharField(blank=True, max_length=32, verbose_name='\u9519\u8bef\u7801')),
                ('failure_msg', models.CharField(blank=True, max_length=128, verbose_name='\u9519\u8bef\u4fe1\u606f')),
                ('charge_order_no', models.CharField(db_index=True, max_length=32, verbose_name='\u5546\u5bb6\u652f\u4ed8\u7f16\u53f7')),
                ('transaction_no', models.CharField(blank=True, max_length=64, verbose_name='\u4e8b\u52a1\u7f16\u53f7')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaolupay.ChargeOrder', verbose_name='\u652f\u4ed8\u8bb0\u5f55')),
            ],
            options={
                'db_table': 'xiaolupay_refund',
                'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u51ed\u8bc1',
                'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u51ed\u8bc1\u5217\u8868',
            },
        ),
    ]
