# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0004_auto_20161130_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeorder',
            name='failure_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u9519\u8bef\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='chargeorder',
            name='failure_msg',
            field=models.CharField(blank=True, max_length=512, verbose_name='\u9519\u8bef\u63cf\u8ff0'),
        ),
    ]
