# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0005_auto_20161217_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeorder',
            name='channel',
            field=models.CharField(choices=[('wx', '\u5fae\u4fe1\u652f\u4ed8'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9d\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053'),
        ),
        migrations.AlterField(
            model_name='chargeorder',
            name='transaction_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u652f\u4ed8\u6e20\u9053\u6d41\u6c34\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='channel',
            field=models.CharField(choices=[('wx', '\u5fae\u4fe1\u652f\u4ed8'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9d\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053'),
        ),
    ]
