# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0006_add_index_to_transaction_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('mch_id', models.CharField(max_length=32, verbose_name='\u5546\u6237\u53f7')),
                ('wxappid', models.CharField(max_length=32, verbose_name='\u516c\u4f17\u53f7appid')),
                ('mch_billno', models.CharField(max_length=32, unique=True, verbose_name='\u5546\u6237\u8ba2\u5355\u53f7')),
                ('payment_no', models.CharField(blank=True, max_length=32, verbose_name='\u5fae\u4fe1\u8ba2\u5355\u53f7')),
                ('openid', models.CharField(db_index=True, max_length=32, verbose_name='\u63a5\u6536\u8005openid')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='\u6536\u6b3e\u4eba\u59d3\u540d')),
                ('amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d(\u5206)')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='\u4f01\u4e1a\u4ed8\u6b3e\u63cf\u8ff0\u4fe1\u606f')),
                ('return_code', models.CharField(max_length=16, verbose_name='\u8fd4\u56de\u72b6\u6001\u7801')),
                ('return_msg', models.CharField(blank=True, max_length=128, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('result_code', models.CharField(blank=True, max_length=16, verbose_name='\u4e1a\u52a1\u7ed3\u679c')),
                ('err_code', models.CharField(blank=True, max_length=32, verbose_name='\u9519\u8bef\u4ee3\u7801')),
                ('err_code_des', models.CharField(blank=True, max_length=128, verbose_name='\u9519\u8bef\u4ee3\u7801\u63cf\u8ff0')),
                ('request_body', models.TextField(verbose_name='\u8bf7\u6c42\u53c2\u6570')),
                ('response_body', models.TextField(verbose_name='\u54cd\u5e94\u7ed3\u679c')),
            ],
            options={
                'db_table': 'xiaolupay_weixin_transfers',
            },
        ),
    ]
