# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0007_create_xiaolupay_weixin_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mch_id', models.CharField(blank=True, max_length=32, verbose_name='\u6e20\u9053\u5546\u6237ID')),
                ('channel', models.CharField(choices=[('wx', '\u5fae\u4fe1APP\u652f\u4ed8'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9dAPP\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8'), ('sandpay', '\u6749\u5fb7\u652f\u4ed8')], db_index=True, default='wx_pub', max_length=16, verbose_name='\u8f6c\u8d26\u6e20\u9053')),
                ('order_code', models.CharField(db_index=True, max_length=32, verbose_name='\u5546\u6237\u8ba2\u5355\u53f7')),
                ('tran_code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='\u6e20\u9053\u6d41\u6c34\u53f7')),
                ('amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d(\u5206)')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='\u4f01\u4e1a\u4ed8\u6b3e\u63cf\u8ff0\u4fe1\u606f')),
                ('return_code', models.CharField(max_length=16, verbose_name='\u8fd4\u56de\u72b6\u6001\u7801')),
                ('return_msg', models.CharField(blank=True, max_length=128, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('status', models.IntegerField(choices=[(0, '\u5904\u7406\u4e2d'), (1, '\u6210\u529f'), (2, '\u5931\u8d25')], db_index=True, default=0, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('uni_key', models.CharField(max_length=64, unique=True, verbose_name='\u552f\u4e00\u952e')),
                ('order_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='\u4e1a\u52a1\u65f6\u95f4')),
                ('expired_time', models.DateTimeField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4')),
                ('success_time', models.DateTimeField(null=True, verbose_name='\u6210\u529f\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('extras', jsonfield.fields.JSONField(default={}, max_length=5012, verbose_name='\u9644\u52a0\u53c2\u6570')),
            ],
            options={
                'db_table': 'xiaolupay_transfer_order',
                'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u4f01\u4e1a\u7edf\u4e00\u8f6c\u8d26',
                'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u4f01\u4e1a\u7edf\u4e00\u8f6c\u8d26',
            },
        ),
        migrations.AlterModelOptions(
            name='weixinredenvelope',
            options={'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u5fae\u4fe1\u73b0\u91d1\u7ea2\u5305', 'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u5fae\u4fe1\u73b0\u91d1\u7ea2\u5305'},
        ),
        migrations.AlterModelOptions(
            name='weixintransfers',
            options={'verbose_name': '\u5c0f\u9e7f\u652f\u4ed8/\u5fae\u4fe1\u4f01\u4e1a\u8f6c\u8d26', 'verbose_name_plural': '\u5c0f\u9e7f\u652f\u4ed8/\u5fae\u4fe1\u4f01\u4e1a\u8f6c\u8d26'},
        ),
        migrations.AlterField(
            model_name='chargeorder',
            name='channel',
            field=models.CharField(choices=[('wx', '\u5fae\u4fe1APP\u652f\u4ed8'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9dAPP\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8'), ('sandpay', '\u6749\u5fb7\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='channel',
            field=models.CharField(choices=[('wx', '\u5fae\u4fe1APP\u652f\u4ed8'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9dAPP\u652f\u4ed8'), ('wx_pub', '\u516c\u4f17\u53f7\u652f\u4ed8'), ('alipay_wap', '\u652f\u4ed8\u5b9d\u7f51\u9875\u652f\u4ed8'), ('upmp_wap', '\u94f6\u8054\u652f\u4ed8'), ('sandpay', '\u6749\u5fb7\u652f\u4ed8')], max_length=16, verbose_name='\u652f\u4ed8\u6e20\u9053'),
        ),
    ]
