# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolupay', '0008_add_transfer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferorder',
            name='expired_time',
        ),
        migrations.AddField(
            model_name='transferorder',
            name='time_out',
            field=models.IntegerField(default=0, verbose_name='\u8d85\u65f6\u65f6\u95f4(s)'),
        ),
    ]
