# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenxiaoProduct',
            fields=[
                ('pid', models.CharField(max_length=64, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=64, blank=True)),
                ('productcat_id', models.CharField(max_length=64, blank=True)),
                ('discount_id', models.CharField(max_length=64, blank=True)),
                ('trade_type', models.CharField(max_length=7, blank=True)),
                ('standard_price', models.CharField(max_length=10, blank=True)),
                ('upshelf_time', models.DateTimeField(null=True)),
                ('is_authz', models.CharField(max_length=3, blank=True)),
                ('properties', models.TextField(max_length=1000, blank=True)),
                ('property_alias', models.TextField(max_length=1000, blank=True)),
                ('input_properties', models.TextField(max_length=1000, blank=True)),
                ('description', models.TextField(max_length=25000, blank=True)),
                ('dealer_cost_price', models.CharField(max_length=10, blank=True)),
                ('item_id', models.CharField(max_length=64, blank=True)),
                ('pdus', models.TextField(max_length=5000, blank=True)),
                ('cost_price', models.CharField(max_length=10, blank=True)),
                ('retail_price_low', models.CharField(max_length=10, blank=True)),
                ('retail_price_high', models.CharField(max_length=10, blank=True)),
                ('outer_id', models.CharField(max_length=64, blank=True)),
                ('quantity', models.IntegerField(null=True)),
                ('alarm_number', models.IntegerField(null=True)),
                ('pictures', models.TextField(max_length=1000, blank=True)),
                ('desc_path', models.CharField(max_length=256, blank=True)),
                ('prov', models.CharField(max_length=16, blank=True)),
                ('city', models.CharField(max_length=16, blank=True)),
                ('postage_id', models.CharField(max_length=64, blank=True)),
                ('postage_type', models.CharField(max_length=10, blank=True)),
                ('postage_ordinary', models.CharField(max_length=10, blank=True)),
                ('postage_fast', models.CharField(max_length=10, blank=True)),
                ('postage_ems', models.CharField(max_length=10, blank=True)),
                ('skus', models.TextField(max_length=5000, blank=True)),
                ('have_invoice', models.BooleanField(default=False)),
                ('have_guarantee', models.BooleanField(default=False)),
                ('items_count', models.IntegerField(null=True)),
                ('orders_count', models.IntegerField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, max_length=10, choices=[(b'up', '\u4e0a\u67b6'), (b'down', '\u4e0b\u67b6')])),
                ('category', models.ForeignKey(related_name='fenxiao_products', to='categorys.Category', null=True)),
                ('user', models.ForeignKey(related_name='fenxiao_products', to='users.User', null=True)),
            ],
            options={
                'db_table': 'shop_fenxiao_product',
                'verbose_name': '\u5206\u9500\u5546\u54c1',
                'verbose_name_plural': '\u5206\u9500\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('fenxiao_id', models.CharField(max_length=64, serialize=False, primary_key=True)),
                ('id', models.CharField(db_index=True, max_length=64, blank=True)),
                ('seller_id', models.CharField(max_length=64, blank=True)),
                ('supplier_username', models.CharField(max_length=64, blank=True)),
                ('supplier_memo', models.TextField(max_length=1000, blank=True)),
                ('supplier_from', models.CharField(max_length=20, blank=True)),
                ('distributor_from', models.CharField(max_length=20, blank=True)),
                ('distributor_username', models.CharField(max_length=32, blank=True)),
                ('distributor_payment', models.FloatField(default=0.0)),
                ('logistics_id', models.CharField(max_length=64, blank=True)),
                ('logistics_company_name', models.CharField(max_length=64, blank=True)),
                ('consign_time', models.DateTimeField(null=True, blank=True)),
                ('pay_time', models.DateTimeField(null=True, blank=True)),
                ('pay_type', models.CharField(blank=True, max_length=32, choices=[(b'ALIPAY_SURETY', '\u652f\u4ed8\u5b9d\u62c5\u4fdd\u4ea4\u6613'), (b'ALIPAY_CHAIN', '\u5206\u8d26\u4ea4\u6613'), (b'TRANSFER', '\u7ebf\u4e0b\u8f6c\u8d26'), (b'PREPAY', '\u9884\u5b58\u6b3e'), (b'IMMEDIATELY', '\u5373\u65f6\u5230\u8d26')])),
                ('post_fee', models.FloatField(default=0.0)),
                ('total_fee', models.FloatField(default=0.0)),
                ('shipping', models.CharField(max_length=10, blank=True)),
                ('trade_type', models.CharField(max_length=10, blank=True)),
                ('memo', models.TextField(max_length=1000, blank=True)),
                ('supplier_flag', models.IntegerField(null=True)),
                ('created', models.DateTimeField(null=True, blank=True)),
                ('modified', models.DateTimeField(null=True, blank=True)),
                ('tc_order_id', models.CharField(max_length=64, blank=True)),
                ('alipay_no', models.CharField(max_length=64, blank=True)),
                ('status', models.CharField(blank=True, max_length=32, choices=[(b'WAIT_BUYER_PAY', '\u7b49\u5f85\u4ed8\u6b3e'), (b'WAIT_SELLER_SEND_GOODS', '\u5df2\u4ed8\u6b3e\uff0c\u5f85\u53d1\u8d27'), (b'WAIT_BUYER_CONFIRM_GOODS', '\u5df2\u4ed8\u6b3e\uff0c\u5df2\u53d1\u8d27'), (b'TRADE_FINISHED', '\u4ea4\u6613\u6210\u529f'), (b'TRADE_CLOSED', '\u4ea4\u6613\u5173\u95ed'), (b'WAIT_BUYER_CONFIRM_GOODS_ACOUNTED', '\u5df2\u4ed8\u6b3e\uff08\u5df2\u5206\u8d26\uff09\uff0c\u5df2\u53d1\u8d27'), (b'WAIT_SELLER_SEND_GOODS_ACOUNTED', '\u5df2\u4ed8\u6b3e\uff08\u5df2\u5206\u8d26\uff09\uff0c\u5f85\u53d1\u8d27')])),
                ('user', models.ForeignKey(related_name='purchases', to='users.User', null=True)),
            ],
            options={
                'db_table': 'shop_fenxiao_purchaseorder',
                'verbose_name': '\u5206\u9500\u8ba2\u5355',
                'verbose_name_plural': '\u5206\u9500\u8ba2\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SubPurchaseOrder',
            fields=[
                ('fenxiao_id', models.CharField(max_length=64, serialize=False, primary_key=True)),
                ('id', models.CharField(max_length=64, blank=True)),
                ('sku_id', models.CharField(max_length=64, blank=True)),
                ('tc_order_id', models.CharField(max_length=64, blank=True)),
                ('item_id', models.CharField(max_length=64, blank=True)),
                ('title', models.CharField(max_length=64, blank=True)),
                ('num', models.IntegerField(null=True)),
                ('price', models.FloatField(default=0.0)),
                ('total_fee', models.FloatField(default=0.0)),
                ('distributor_payment', models.FloatField(default=0.0)),
                ('buyer_payment', models.FloatField(default=0.0)),
                ('order_200_status', models.CharField(max_length=32, blank=True)),
                ('auction_price', models.FloatField(default=0.0)),
                ('old_sku_properties', models.TextField(max_length=1000, blank=True)),
                ('item_outer_id', models.CharField(max_length=64, blank=True)),
                ('sku_outer_id', models.CharField(max_length=64, blank=True)),
                ('sku_properties', models.TextField(max_length=1000, blank=True)),
                ('snapshot_url', models.CharField(max_length=256, blank=True)),
                ('created', models.DateTimeField(null=True)),
                ('refund_fee', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, max_length=32, choices=[(b'WAIT_BUYER_PAY', '\u7b49\u5f85\u4ed8\u6b3e'), (b'WAIT_CONFIRM', '\u4ed8\u6b3e\u4fe1\u606f\u5f85\u786e\u8ba4'), (b'WAIT_CONFIRM_WAIT_SEND_GOODS', '\u4ed8\u6b3e\u4fe1\u606f\u5f85\u786e\u8ba4\uff0c\u5f85\u53d1\u8d27'), (b'WAIT_CONFIRM_SEND_GOODS', '\u4ed8\u6b3e\u4fe1\u606f\u5f85\u786e\u8ba4\uff0c\u5df2\u53d1\u8d27'), (b'WAIT_CONFIRM_GOODS_CONFIRM', '\u4ed8\u6b3e\u4fe1\u606f\u5f85\u786e\u8ba4\uff0c\u5df2\u6536\u8d27'), (b'WAIT_SELLER_SEND_GOODS', '\u5df2\u4ed8\u6b3e\uff0c\u5f85\u53d1\u8d27'), (b'WAIT_BUYER_CONFIRM_GOODS', '\u5df2\u4ed8\u6b3e\uff0c\u5df2\u53d1\u8d27'), (b'CONFIRM_WAIT_SEND_GOODS', '\u4ed8\u6b3e\u4fe1\u606f\u5df2\u786e\u8ba4\uff0c\u5f85\u53d1\u8d27'), (b'CONFIRM_SEND_GOODS', '\u4ed8\u6b3e\u4fe1\u606f\u5df2\u786e\u8ba4\uff0c\u5df2\u53d1\u8d27'), (b'TRADE_REFUNDED', '\u5df2\u9000\u6b3e'), (b'TRADE_REFUNDING', '\u9000\u6b3e\u4e2d'), (b'TRADE_FINISHED', '\u4ea4\u6613\u6210\u529f'), (b'TRADE_CLOSED', '\u4ea4\u6613\u5173\u95ed')])),
                ('fenxiao_product', models.ForeignKey(related_name='sub_purchase_orders', to='fenxiao.FenxiaoProduct', null=True)),
                ('purchase_order', models.ForeignKey(related_name='sub_purchase_orders', to='fenxiao.PurchaseOrder', null=True)),
            ],
            options={
                'db_table': 'shop_fenxiao_subpurchaseorder',
                'verbose_name': '\u5206\u9500\u8ba2\u5355\u5546\u54c1',
                'verbose_name_plural': '\u5206\u9500\u8ba2\u5355\u5546\u54c1\u5217\u8868',
            },
        ),
    ]
