# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0036_salesupplier_stocking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='stocking_mode',
            field=models.IntegerField(choices=[(0, '\u672a\u5907\u8d27'), (1, '\u5907\u8d27')], db_index=True, default=0, verbose_name='\u5b58\u8d27\u6a21\u5f0f'),
        ),
    ]
