# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0037_supplier_stocking_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='remain_num',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='extras',
            field=jsonfield.fields.JSONField(default={}, max_length=512, verbose_name='\u9644\u52a0\u4fe1\u606f'),
        ),
    ]
