# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0040_add_field_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='source_type',
            field=models.IntegerField(choices=[(0, '\u81ea\u50a8\u5546\u54c1'), (1, '\u7b2c\u4e09\u65b9\u4ed3'), (2, '\u4fdd\u7a0e\u4ed3'), (3, '\u5173\u5916\u76f4\u90ae')], db_index=True, default=0, verbose_name='\u5546\u54c1\u8d27\u6e90'),
        ),
    ]
