# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0042_salecategory_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesupplier',
            name='vendor_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='\u540e\u9762\u5e94\u6539\u4e3aunique', max_length=32, verbose_name='\u4f9b\u5e94\u5546\u7f16\u7801'),
        ),
    ]
