# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0045_change_vendor_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesupplier',
            name='can_change_logistics',
            field=models.BooleanField(default=False, verbose_name='\u81ea\u9009\u7269\u6d41'),
        ),
    ]
