# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0046_salesupplier_can_change_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproductmanagedetail',
            name='model_product_id',
            field=models.BigIntegerField(default=0, verbose_name='\u552e\u5356\u6b3e\u5f0fID'),
        ),
        migrations.AlterField(
            model_name='salecategoryversion',
            name='download_url',
            field=models.CharField(blank=True, help_text='\u4e0d\u7528\u586b\u5199,\u7b2c\u4e8c\u6b21\u4fdd\u5b58\u65f6\u4f1a\u81ea\u52a8\u751f\u6210', max_length=256, verbose_name='\u4e0b\u8f7d\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='salecategoryversion',
            name='memo',
            field=models.TextField(blank=True, help_text='\u9700\u586b\u5199', verbose_name='\u5907\u6ce8'),
        )
    ]
