# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCashoutRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='ID', db_index=True)),
                ('cashout_value', models.IntegerField()),
                ('cashout_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'cashout time')),
            ],
            options={
                'db_table': 'shop_weixin_bonus_cashout_record',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=256, verbose_name='\u63cf\u8ff0', blank=True)),
                ('coupon_url', models.URLField(verbose_name=b'\xe9\xa2\x86\xe5\x8f\x96\xe9\x93\xbe\xe6\x8e\xa5', blank=True)),
                ('face_value', models.IntegerField(default=0, verbose_name='\u9762\u503c')),
                ('expiry', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_coupon',
                'verbose_name': '\u4f18\u60e0\u5238',
                'verbose_name_plural': '\u4f18\u60e0\u5238\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='CouponClick',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
                ('vipcode', models.CharField(max_length=16, verbose_name='VIP\u9080\u8bf7\u7801')),
                ('coupon', models.ForeignKey(related_name='clicks', verbose_name='\u4f18\u60e0\u5238', to='weixin.Coupon')),
            ],
            options={
                'db_table': 'shop_weixin_coupon_click',
                'verbose_name': '\u4f18\u60e0\u5238\u70b9\u51fb',
                'verbose_name_plural': '\u4f18\u60e0\u5238\u70b9\u51fb\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('paper_title', models.CharField(max_length=200, verbose_name='\u5377\u6807', blank=True)),
                ('problem_num', models.IntegerField(null=True, verbose_name='\u9898\u76ee\u6570', db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u8349\u7a3f'), (1, '\u8fdb\u884c\u4e2d'), (2, '\u5df2\u53d6\u6d88'), (3, '\u5df2\u7ed3\u675f')])),
            ],
            options={
                'db_table': 'shop_weixin_exam_paper',
                'verbose_name': '\u5fae\u4fe1\u8003\u8bd5\u7b54\u5377',
                'verbose_name_plural': '\u5fae\u4fe1\u8003\u8bd5\u7b54\u5377\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ExamProblem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('problem_title', models.CharField(max_length=1500, verbose_name='\u9898\u76ee', blank=True)),
                ('problem_answer', models.CharField(max_length=4, verbose_name='\u6b63\u786e\u9009\u9879', blank=True)),
                ('option_a', models.CharField(max_length=200, verbose_name='\u9009\u9879A', blank=True)),
                ('option_b', models.CharField(max_length=200, verbose_name='\u9009\u9879B', blank=True)),
                ('option_c', models.CharField(max_length=200, verbose_name='\u9009\u9879C', blank=True)),
                ('option_d', models.CharField(max_length=200, verbose_name='\u9009\u9879D', blank=True)),
                ('problem_score', models.IntegerField(default=1, verbose_name='\u9898\u76ee\u5206\u6570')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u4f7f\u7528'), (1, '\u5f85\u7528')])),
            ],
            options={
                'db_table': 'shop_weixin_exam_problem',
                'verbose_name': '\u5fae\u4fe1\u8003\u8bd5\u9898\u5e93',
                'verbose_name_plural': '\u5fae\u4fe1\u8003\u8bd5\u9898\u5e93\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ExamUserPaper',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('paper_id', models.CharField(max_length=100, verbose_name='\u5377', blank=True)),
                ('answer_num', models.IntegerField(default=0, verbose_name='\u7b54\u9898\u6570')),
                ('grade', models.IntegerField(default=0, verbose_name='\u8003\u8bd5\u5f97\u5206')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe7\xad\x94\xe9\xa2\x98\xe6\x97\xa5\xe6\x9c\x9f', null=True)),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')])),
            ],
            options={
                'db_table': 'shop_weixin_exam_user_paper',
                'verbose_name': '\u7528\u6237\u7b54\u5377',
                'verbose_name_plural': '\u7528\u6237\u7b54\u5377\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ExamUserProblem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID')),
                ('paper_id', models.IntegerField(verbose_name='\u5377\u7801', db_index=True)),
                ('problem_id', models.IntegerField(verbose_name='\u9898\u7801', db_index=True)),
                ('selected', models.CharField(blank=True, max_length=10, verbose_name='\u7b54\u9898\u4eba\u9009\u9879', choices=[(b'A', 'A'), (b'B', 'B'), (b'C', 'C'), (b'D', 'D')])),
                ('problem_score', models.IntegerField(null=True, verbose_name='\u9898\u76ee\u5206\u6570', db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u7b54\u9898\u65f6\u95f4', null=True)),
                ('status', models.BooleanField(default=False, verbose_name='\u56de\u7b54\u6b63\u786e')),
            ],
            options={
                'db_table': 'shop_weixin_exam_user_problem',
                'verbose_name': '\u7528\u6237\u7b54\u9898',
                'verbose_name_plural': '\u7528\u6237\u7b54\u9898\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='FreeSample',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('outer_id', models.CharField(unique=True, max_length=32, verbose_name='\u5916\u90e8\u7f16\u7801', blank=True)),
                ('name', models.CharField(max_length=64, verbose_name='\u5546\u54c1\u540d\u79f0', blank=True)),
                ('expiry', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('stock', models.IntegerField(default=0, verbose_name='\u5e93\u5b58')),
                ('pic_url', models.URLField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x9b\xbe\xe7\x89\x87', blank=True)),
                ('sale_url', models.URLField(verbose_name=b'\xe9\x94\x80\xe5\x94\xae\xe9\x93\xbe\xe6\x8e\xa5', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_free_sample',
                'verbose_name': '\u8bd5\u7528\u5546\u54c1',
                'verbose_name_plural': '\u8bd5\u7528\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Invitationship',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('from_openid', models.CharField(max_length=64, verbose_name='\u9080\u8bf7\u4eba\u5fae\u4fe1ID')),
                ('invite_openid', models.CharField(max_length=64, verbose_name='\u88ab\u9080\u8bf7\u5fae\u4fe1ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_exam_invitationship',
                'verbose_name': '\u7b54\u9898\u5173\u7cfb',
                'verbose_name_plural': '\u7b54\u9898\u5173\u7cfb\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ReferalBonusRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('referal_user_openid', models.CharField(max_length=64, verbose_name='\u88ab\u63a8\u8350\u4eba\u5fae\u4fe1ID', db_index=True)),
                ('trade_id', models.IntegerField(default=0, unique=True, verbose_name='\u8ba2\u5355\u53f7', db_index=True)),
                ('bonus_value', models.IntegerField(default=0, verbose_name='\u91d1\u989d\uff08\u5206\uff09')),
                ('confirmed_status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u672a\u77e5'), (1, '\u786e\u5b9a'), (2, '\u53d6\u6d88')])),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'shop_weixin_referal_bonus_record',
                'verbose_name': '\u5927\u4f7f\u8fd4\u5229',
                'verbose_name_plural': '\u5927\u4f7f\u8fd4\u5229\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ReferalRelationship',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('referal_from_openid', models.CharField(max_length=64, verbose_name='\u63a8\u8350\u4ebaID', db_index=True)),
                ('referal_to_mobile', models.CharField(max_length=12, verbose_name='\u88ab\u63a8\u8350\u4eba\u624b\u673a', db_index=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'time created')),
            ],
            options={
                'db_table': 'shop_weixin_referal_relationship',
            },
        ),
        migrations.CreateModel(
            name='ReferalSummary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(unique=True, max_length=64, verbose_name='ID', db_index=True)),
                ('total_confirmed_value', models.IntegerField(default=0)),
                ('cashed_value', models.IntegerField(default=0)),
                ('direct_referal_count', models.IntegerField(default=0)),
                ('indirect_referal_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_weixin_referal_summary',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('mobile', models.CharField(max_length=24, verbose_name='\u624b\u673a', blank=True)),
                ('trade_id', models.IntegerField(default=0, unique=True, verbose_name='\u8ba2\u5355ID')),
                ('refund_type', models.IntegerField(default=0, verbose_name='\u8fd4\u5229\u7c7b\u578b', choices=[(0, '\u6652\u5355\u8fd4\u73b0'), (1, 'VIP\u9080\u8bf7'), (2, '10\u79ef\u5206\u6362\u8d2d'), (3, '\u6ee1100\u5143\u8fd410\u5143'), (4, '100\u5143\u514d\u5355'), (5, '10\u79ef\u5206\u8fd4\u90ae\u8d39')])),
                ('pay_type', models.IntegerField(default=0, verbose_name='\u652f\u4ed8\u65b9\u5f0f', choices=[(0, '\u7533\u8bf7\u9000\u6b3e'), (1, '\u9000\u90ae\u8d39'), (2, '\u652f\u4ed8\u5b9d\u8f6c\u8d26'), (3, '\u94f6\u884c\u8f6c\u8d26')])),
                ('vip_code', models.CharField(max_length=10, verbose_name='VIP\u9080\u8bf7\u7801', blank=True)),
                ('pay_amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d')),
                ('refund_status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u7b49\u5f85\u5ba1\u6838'), (1, '\u5ba1\u6838\u901a\u8fc7'), (2, '\u5ba1\u6838\u4e0d\u901a\u8fc7'), (3, '\u5b8c\u6210')])),
                ('review_note', models.CharField(max_length=256, verbose_name='\u5ba1\u6838\u5907\u6ce8', blank=True)),
                ('pay_note', models.CharField(max_length=256, verbose_name='\u8fd4\u73b0\u5907\u6ce8', blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7533\u8bf7\u65e5\u671f', db_index=True)),
                ('pay_time', models.DateTimeField(db_index=True, null=True, verbose_name='\u4ed8\u6b3e\u65e5\u671f', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_refund',
                'verbose_name': '\u8fd4\u73b0\u8ba2\u5355',
                'verbose_name_plural': '\u8fd4\u73b0\u8ba2\u5355\u5217\u8868',
                'permissions': [('can_refund_agree', '\u8fd4\u73b0\u8ba2\u5355\u5ba1\u6838\u6743\u9650'), ('can_refund_confirm', '\u8fd4\u73b0\u8ba2\u5355\u652f\u4ed8\u786e\u8ba4\u6743\u9650')],
            },
        ),
        migrations.CreateModel(
            name='SampleChoose',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(unique=True, max_length=64, verbose_name='\u5fae\u4fe1ID')),
                ('vipcode', models.CharField(max_length=16, verbose_name='VIP\u9080\u8bf7\u7801')),
                ('mobile', models.CharField(max_length=24, verbose_name='\u624b\u673a', blank=True)),
                ('selection', models.IntegerField(default=0, verbose_name='\u9009\u62e9', choices=[(1, '\u6597\u7bf7'), (2, '\u7761\u888b')])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_sample_choose',
                'verbose_name': '\u8bd5\u7528\u5546\u54c1\u9009\u62e9',
                'verbose_name_plural': '\u8bd5\u7528\u5546\u54c1\u9009\u62e9\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SampleFrozenScore',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1\u7528\u6237ID', db_index=True)),
                ('sample_id', models.IntegerField(unique=True, verbose_name='\u8bd5\u7528\u8ba2\u5355ID')),
                ('frozen_score', models.IntegerField(default=0, verbose_name='\u51bb\u7ed3\u79ef\u5206')),
                ('frozen_time', models.DateTimeField(null=True, verbose_name='\u51bb\u7ed3\u622a\u6b62', blank=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u51bb\u7ed3'), (1, '\u53d6\u6d88'), (2, '\u5b8c\u6210')])),
            ],
            options={
                'db_table': 'shop_weixin_score_frozen',
                'verbose_name': '\u8bd5\u7528\u51bb\u7ed3\u79ef\u5206',
                'verbose_name_plural': '\u4f7f\u7528\u51bb\u7ed3\u79ef\u5206\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SampleOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sku_code', models.CharField(max_length=32, verbose_name='SKU\u7f16\u7801', blank=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4', db_index=True)),
                ('vipcode', models.CharField(max_length=16, verbose_name='VIP\u9080\u8bf7\u7801', db_index=True)),
                ('problem_score', models.IntegerField(default=0, verbose_name='\u7b54\u9898\u5206\u6570')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', db_index=True)),
                ('sample_product', models.ForeignKey(related_name='sample_orders', verbose_name='\u8bd5\u7528\u5546\u54c1', to='weixin.FreeSample')),
            ],
            options={
                'db_table': 'shop_weixin_sample_order',
                'verbose_name': '\u8bd5\u7528\u7533\u8bf7',
                'verbose_name_plural': '\u8bd5\u7528\u7533\u8bf7\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SampleSku',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sku_code', models.CharField(max_length=32, verbose_name='SKU\u7f16\u7801', blank=True)),
                ('sku_name', models.CharField(max_length=64, verbose_name='\u6b3e\u5f0f\u5c3a\u5bf8', blank=True)),
                ('sample_product', models.ForeignKey(related_name='skus', verbose_name='\u8bd5\u7528\u5546\u54c1', to='weixin.FreeSample')),
            ],
            options={
                'db_table': 'shop_weixin_sample_sku',
                'verbose_name': '\u8bd5\u7528\u5546\u54c1SKU',
                'verbose_name_plural': '\u8bd5\u7528\u5546\u54c1SKU\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('selection', models.IntegerField(default=0, verbose_name='\u9009\u62e9')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_survey',
                'verbose_name': '\u7528\u6237\u8c03\u7814',
                'verbose_name_plural': '\u7528\u6237\u8c03\u7814\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='TradeScoreRelevance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('trade_id', models.CharField(unique=True, max_length=64, verbose_name='\u4ea4\u6613ID')),
                ('mobile', models.CharField(db_index=True, max_length=36, verbose_name='\u624b\u673a', blank=True)),
                ('payment', models.IntegerField(default=0, verbose_name='\u4ed8\u6b3e\u91d1\u989d')),
                ('is_used', models.BooleanField(default=False, verbose_name='\u4f7f\u7528')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_trade_score_relate',
                'verbose_name': '\u4ea4\u6613\u79ef\u5206\u5173\u8054',
                'verbose_name_plural': '\u4ea4\u6613\u79ef\u5206\u5173\u8054\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=32, verbose_name='\u7ec4\u4ee3\u7801', blank=True)),
                ('name', models.CharField(max_length=32, verbose_name='\u7ec4\u540d', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_group',
                'verbose_name': '\u7528\u6237\u5206\u7ec4',
                'verbose_name_plural': '\u7528\u6237\u5206\u7ec4\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(unique=True, max_length=16, verbose_name='F\u7801')),
                ('expiry', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('code_type', models.IntegerField(default=0, verbose_name='\u652f\u4ed8\u65b9\u5f0f', choices=[(0, '\u8bd5\u7528'), (1, '\u8d2d\u4e70')])),
                ('code_rule', models.CharField(max_length=256, verbose_name='\u4f7f\u7528\u89c4\u5219', blank=True)),
                ('max_usage', models.IntegerField(default=0, verbose_name='\u53ef\u7528\u6b21\u6570')),
                ('usage_count', models.IntegerField(default=0, verbose_name='\u5df2\u4f7f\u7528', db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_vipcode',
                'verbose_name': 'VIP\u9080\u8bf7\u7801',
                'verbose_name_plural': 'VIP\u9080\u8bf7\u7801\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeiXinAccount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('account_id', models.CharField(unique=True, max_length=32, verbose_name='OPEN ID')),
                ('token', models.CharField(max_length=32, verbose_name='TOKEN')),
                ('app_id', models.CharField(max_length=64, verbose_name='\u5e94\u7528ID')),
                ('app_secret', models.CharField(max_length=128, verbose_name='\u5e94\u7528SECRET')),
                ('pay_sign_key', models.CharField(max_length=128, verbose_name='\u652f\u4ed8\u5bc6\u94a5')),
                ('partner_id', models.CharField(max_length=32, verbose_name='\u5546\u6237ID')),
                ('partner_key', models.CharField(max_length=128, verbose_name='\u5546\u6237KEY')),
                ('access_token', models.CharField(max_length=256, verbose_name='ACCESS TOKEN', blank=True)),
                ('js_ticket', models.CharField(max_length=256, verbose_name='JSAPI_TICKET', blank=True)),
                ('expires_in', models.BigIntegerField(default=0, verbose_name=b'\xe4\xbd\xbf\xe7\x94\xa8\xe6\x9c\x9f\xe9\x99\x90(s)')),
                ('expired', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe8\xbf\x87\xe6\x9c\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('js_expired', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'TICKET\xe4\xb8\x8a\xe6\xac\xa1\xe8\xbf\x87\xe6\x9c\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('jmenu', jsonfield.fields.JSONField(default={}, max_length=4096, verbose_name='\u83dc\u5355\u4ee3\u7801', blank=True)),
                ('in_voice', models.BooleanField(default=False, verbose_name='\u5f00\u542f\u8bed\u97f3')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6fc0\u6d3b')),
                ('order_updated', models.DateTimeField(null=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', blank=True)),
                ('refund_updated', models.DateTimeField(null=True, verbose_name=b'\xe7\xbb\xb4\xe6\x9d\x83\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_account',
                'verbose_name': '\u5fae\u4fe1\u670d\u52a1\u5e10\u53f7',
                'verbose_name_plural': '\u5fae\u4fe1\u670d\u52a1\u5e10\u53f7\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeiXinAutoResponse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('message', models.CharField(unique=True, max_length=64, verbose_name='\u6d88\u606f')),
                ('rtype', models.CharField(default=b'text', max_length=8, verbose_name='\u7c7b\u578b', choices=[(b'text', '\u6587\u672c'), (b'image', '\u56fe\u7247'), (b'voice', '\u8bed\u97f3'), (b'video', '\u89c6\u9891'), (b'thumb', '\u7f29\u7565\u56fe'), (b'music', '\u97f3\u4e50'), (b'news', '\u65b0\u95fb')])),
                ('media_id', models.CharField(max_length=1024, verbose_name='\u5a92\u4f53ID', blank=True)),
                ('title', models.CharField(max_length=512, verbose_name='\u6807\u9898', blank=True)),
                ('content', models.CharField(max_length=4096, verbose_name='\u56de\u590d\u4fe1\u606f', blank=True)),
                ('music_url', models.CharField(max_length=512, verbose_name='\u97f3\u4e50\u94fe\u63a5', blank=True)),
                ('hq_music_url', models.CharField(max_length=512, verbose_name='\u9ad8\u54c1\u8d28\u97f3\u4e50\u94fe\u63a5', blank=True)),
                ('news_json', jsonfield.fields.JSONField(default={}, max_length=8192, verbose_name='\u56fe\u6587\u4fe1\u606f', blank=True)),
                ('fuzzy_match', models.BooleanField(default=True, verbose_name='\u6a21\u7cca\u5339\u914d')),
            ],
            options={
                'db_table': 'shop_weixin_response',
                'verbose_name': '\u5fae\u4fe1\u56de\u590d',
                'verbose_name_plural': '\u5fae\u4fe1\u56de\u590d\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinClickScore',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('description', models.CharField(max_length=64, verbose_name='\u63cf\u8ff0')),
                ('redirect_link', models.URLField(verbose_name='\u8df3\u8f6c\u94fe\u63a5', blank=True)),
                ('score', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u6570')),
                ('expiry', models.DateTimeField(null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4', blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_click_score',
                'verbose_name': '\u79ef\u5206\u94fe\u63a5',
                'verbose_name_plural': '\u79ef\u5206\u94fe\u63a5\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinClickScoreRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('click_score_id', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u94fe\u63a5ID')),
                ('score', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u6570')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_click_score_item',
                'verbose_name': '\u79ef\u5206\u94fe\u63a5\u70b9\u51fb',
                'verbose_name_plural': '\u79ef\u5206\u94fe\u63a5\u70b9\u51fb\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinLinkClickRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u7533\u8bf7\u4ebaID', db_index=True)),
                ('link_url', models.CharField(max_length=128, verbose_name='\u70b9\u51fb\u94fe\u63a5', db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_sale_clickrecord',
                'verbose_name': '\u5fae\u4fe1\u70b9\u51fb\u8bb0\u5f55',
                'verbose_name_plural': '\u5fae\u4fe1\u70b9\u51fb\u8bb0\u5f55\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinLinkClicks',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='OPEN ID')),
                ('link_url', models.CharField(db_index=True, max_length=128, verbose_name='\u5206\u4eab\u94fe\u63a5', blank=True)),
                ('link_type', models.CharField(default=b'sample', max_length=8, verbose_name='\u94fe\u63a5\u7c7b\u578b', db_index=True, choices=[(b'sample', '\u8bd5\u7528\u94fe\u63a5'), (b'sale', '\u7279\u5356\u94fe\u63a5')])),
                ('clicker_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u4eba\u6570')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('validated_in', models.IntegerField(default=0, verbose_name='\u6709\u6548\u95f4\u9694(s)')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_sale_linkclicks',
                'verbose_name': '\u5fae\u4fe1\u5206\u4eab\u70b9\u51fb',
                'verbose_name_plural': '\u5fae\u4fe1\u5206\u4eab\u70b9\u51fb\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinLinkShare',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='OPEN ID', db_index=True)),
                ('link_url', models.CharField(db_index=True, max_length=128, verbose_name='\u5206\u4eab\u94fe\u63a5', blank=True)),
                ('link_type', models.CharField(db_index=True, max_length=8, verbose_name='\u5206\u4eab\u7c7b\u578b', choices=[(b'APP', '\u5fae\u4fe1\u597d\u53cb'), (b'PYQ', '\u670b\u53cb\u5708'), (b'QQ', 'QQ'), (b'WB', '\u5fae\u535a')])),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_sale_linkshare',
                'verbose_name': '\u5fae\u4fe1\u5206\u4eab\u94fe\u63a5',
                'verbose_name_plural': '\u5fae\u4fe1\u5206\u4eab\u94fe\u63a5\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinScoreBuy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('buy_score', models.PositiveIntegerField(default=0, verbose_name='\u6362\u8d2d\u79ef\u5206')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
                ('batch', models.IntegerField(default=0, verbose_name='\u6279\u6b21')),
            ],
            options={
                'db_table': 'shop_weixin_scorebuy',
                'verbose_name': '\u79ef\u5206\u6362\u8d2d\u540d\u5355',
                'verbose_name_plural': '\u79ef\u5206\u6362\u8d2d\u540d\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinScoreItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1ID', db_index=True)),
                ('score', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u53d8\u5316')),
                ('score_type', models.IntegerField(default=0, db_index=True, verbose_name='\u79ef\u5206\u7c7b\u578b', choices=[(-3, '\u51bb\u7ed3\u79ef\u5206'), (-1, '\u8fd4\u73b0\u6d88\u8d39'), (2, '\u8d2d\u7269\u79ef\u5206'), (1, '\u9080\u8bf7\u79ef\u5206'), (3, '\u6d3b\u52a8\u79ef\u5206'), (-2, '\u4e2d\u5956\u6263\u9664'), (4, '\u9605\u8bfb\u70b9\u51fb'), (0, '\u5176\u5b83')])),
                ('expired_at', models.DateTimeField(null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4', blank=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
                ('memo', models.CharField(db_index=True, max_length=64, verbose_name='\u53d8\u66f4\u5907\u6ce8', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_score_item',
                'verbose_name': '\u7528\u6237\u79ef\u5206\u660e\u7ec6',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206\u660e\u7ec6\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinUnionID',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f', db_index=True)),
                ('openid', models.CharField(max_length=32, verbose_name='OPENID')),
                ('app_key', models.CharField(max_length=24, verbose_name='APPKEY')),
                ('unionid', models.CharField(max_length=32, verbose_name='UNIONID', db_index=True)),
            ],
            options={
                'db_table': 'shop_weixin_unionid',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237\u6388\u6743ID',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u6388\u6743ID\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeiXinUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f', db_index=True)),
                ('openid', models.CharField(unique=True, max_length=64, verbose_name='\u7528\u6237ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='\u6635\u79f0', blank=True)),
                ('unionid', models.CharField(db_index=True, max_length=64, verbose_name='UnionID', blank=True)),
                ('sex', models.IntegerField(default=0, verbose_name='\u6027\u522b', choices=[(1, '\u7537'), (2, '\u5973')])),
                ('language', models.CharField(max_length=10, verbose_name='\u8bed\u8a00', blank=True)),
                ('headimgurl', models.URLField(verbose_name='\u5934\u50cf', blank=True)),
                ('country', models.CharField(max_length=24, verbose_name='\u56fd\u5bb6', blank=True)),
                ('province', models.CharField(max_length=24, verbose_name='\u7701\u4efd', blank=True)),
                ('city', models.CharField(max_length=24, verbose_name='\u57ce\u5e02', blank=True)),
                ('address', models.CharField(max_length=256, verbose_name='\u5730\u5740', blank=True)),
                ('mobile', models.CharField(db_index=True, max_length=11, verbose_name='\u624b\u673a', blank=True)),
                ('referal_from_openid', models.CharField(db_index=True, max_length=64, verbose_name='\u63a8\u8350\u4ebaID', blank=True)),
                ('receiver_name', models.CharField(max_length=64, verbose_name='\u6536\u8d27\u4eba', blank=True)),
                ('birth_year', models.IntegerField(default=0, verbose_name='\u51fa\u751f\u5e74')),
                ('birth_month', models.IntegerField(default=0, verbose_name='\u51fa\u751f\u6708')),
                ('baby_sex', models.CharField(blank=True, max_length=1, verbose_name='\u5b9d\u5b9d\u6027\u522b', choices=[(b'm', '\u7537'), (b'f', '\u5973')])),
                ('baby_topic', models.CharField(max_length=256, verbose_name='\u5b9d\u5b9d\u7b7e\u540d', blank=True)),
                ('vmobile', models.CharField(db_index=True, max_length=11, verbose_name='\u5f85\u9a8c\u8bc1\u624b\u673a', blank=True)),
                ('isvalid', models.BooleanField(default=False, verbose_name='\u5df2\u9a8c\u8bc1')),
                ('validcode', models.CharField(max_length=6, verbose_name='\u9a8c\u8bc1\u7801', blank=True)),
                ('valid_count', models.IntegerField(default=0, verbose_name='\u9a8c\u8bc1\u6b21\u6570')),
                ('code_time', models.DateTimeField(null=True, verbose_name='\u77ed\u4fe1\u53d1\u9001\u65f6\u95f4', blank=True)),
                ('sceneid', models.CharField(max_length=32, verbose_name='\u573a\u666fID', blank=True)),
                ('subscribe', models.BooleanField(default=False, verbose_name='\u8ba2\u9605\u8be5\u53f7')),
                ('subscribe_time', models.DateTimeField(null=True, verbose_name='\u8ba2\u9605\u65f6\u95f4', blank=True)),
                ('referal_count', models.IntegerField(default=0, verbose_name='F\u7801\u6b21\u6570')),
                ('charge_status', models.CharField(default=b'uncharge', choices=[(b'uncharge', '\u5f85\u63a5\u7ba1'), (b'charged', '\u5df2\u63a5\u7ba1'), (b'frozen', '\u5df2\u51bb\u7ed3')], max_length=16, blank=True, verbose_name='\u63a5\u7ba1\u72b6\u6001', db_index=True)),
                ('user_group', models.ForeignKey(verbose_name='\u5206\u7ec4', blank=True, to='weixin.UserGroup', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_user',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinUserAward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(unique=True, max_length=64, verbose_name='\u7533\u8bf7\u4ebaID')),
                ('referal_from_openid', models.CharField(db_index=True, max_length=64, verbose_name='\u9080\u8bf7\u4ebaID', blank=True)),
                ('is_receive', models.BooleanField(default=False, verbose_name='\u9886\u53d6')),
                ('is_share', models.BooleanField(default=False, verbose_name='\u53d1\u9001')),
                ('is_notify', models.BooleanField(default=False, verbose_name='\u63d0\u9192\u901a\u77e5')),
                ('remind_count', models.IntegerField(default=0, verbose_name='\u63d0\u9192\u6b21\u6570')),
                ('remind_time', models.DateTimeField(null=True, verbose_name='\u63d0\u9192\u65f6\u95f4', blank=True)),
                ('select_val', models.IntegerField(default=0, verbose_name='\u9009\u62e9\u503c')),
                ('award_val', models.IntegerField(default=0, verbose_name='\u5956\u52b1\u503c')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_user_award',
                'verbose_name': '\u5fae\u4fe1\u9080\u8bf7\u5956\u52b1',
                'verbose_name_plural': '\u5fae\u4fe1\u9080\u8bf7\u5956\u52b1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinUserInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f', db_index=True)),
                ('unionid', models.CharField(unique=True, max_length=32, verbose_name='UNIONID')),
                ('nick', models.CharField(max_length=32, verbose_name='\u6635\u79f0', blank=True)),
                ('thumbnail', models.CharField(max_length=256, verbose_name='\u5934\u50cf', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_userinfo',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u57fa\u672c\u4fe1\u606f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinUserPicture',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(max_length=64, verbose_name='\u7528\u6237ID', db_index=True)),
                ('mobile', models.CharField(db_index=True, max_length=12, verbose_name='\u624b\u673a', blank=True)),
                ('pic_url', models.URLField(max_length=1024, verbose_name='\u56fe\u7247URL', blank=True)),
                ('pic_type', models.CharField(default=b'OTHER', max_length=8, verbose_name='\u56fe\u7247\u7c7b\u578b', choices=[(b'SDPP', '\u6652\u5355\u622a\u56fe'), (b'HPPP', '\u597d\u8bc4\u622a\u56fe'), (b'BBPP', '\u5b9d\u5b9d\u79c0'), (b'OTHER', '\u5176\u5b83')])),
                ('pic_num', models.IntegerField(default=0, verbose_name='\u56fe\u7247\u5f20\u6570')),
                ('upload_ended', models.DateTimeField(null=True, verbose_name='\u4e0a\u4f20\u6709\u6548\u65f6\u95f4', blank=True)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f', null=True)),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001', choices=[(0, '\u7533\u8bf7\u4e2d'), (1, '\u5df2\u63d0\u4ea4'), (2, '\u5df2\u53d6\u6d88')])),
            ],
            options={
                'db_table': 'shop_weixin_user_picture',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237\u56fe\u7247',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u56fe\u7247\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WeixinUserScore',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_openid', models.CharField(unique=True, max_length=64, verbose_name='\u5fae\u4fe1ID')),
                ('user_score', models.PositiveIntegerField(default=0, verbose_name='\u5269\u4f59\u79ef\u5206')),
                ('expiring_score', models.PositiveIntegerField(default=0, verbose_name='\u5373\u5c06\u8fc7\u671f\u79ef\u5206')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4', null=True)),
            ],
            options={
                'db_table': 'shop_weixin_user_score',
                'verbose_name': '\u7528\u6237\u79ef\u5206',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXLogistic',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company_name', models.CharField(max_length=16, verbose_name='\u5feb\u9012\u540d\u79f0', blank=True)),
                ('origin_code', models.CharField(max_length=16, verbose_name='\u539f\u59cb\u7f16\u7801', blank=True)),
                ('company_code', models.CharField(max_length=16, verbose_name='\u5feb\u9012\u7f16\u7801', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_logistic',
                'verbose_name': '\u5fae\u4fe1\u5c0f\u5e97\u5feb\u9012',
                'verbose_name_plural': '\u5fae\u4fe1\u5c0f\u5e97\u5feb\u9012\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXOrder',
            fields=[
                ('order_id', models.CharField(max_length=32, serialize=False, verbose_name='\u8ba2\u5355ID', primary_key=True)),
                ('trans_id', models.CharField(max_length=32, verbose_name='\u4ea4\u6613ID', blank=True)),
                ('seller_id', models.CharField(max_length=32, verbose_name='\u5546\u5bb6ID', db_index=True)),
                ('buyer_openid', models.CharField(db_index=True, max_length=64, verbose_name='\u4e70\u5bb6OPENID', blank=True)),
                ('buyer_nick', models.CharField(db_index=True, max_length=32, verbose_name='\u4e70\u5bb6\u6635\u79f0', blank=True)),
                ('order_total_price', models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u603b\u4ef7(\u5206)')),
                ('order_express_price', models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u8fd0\u8d39(\u5206)')),
                ('order_create_time', models.DateTimeField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4', blank=True)),
                ('order_status', models.IntegerField(default=1, verbose_name='\u8ba2\u5355\u72b6\u6001', choices=[(1, '\u5f85\u4ed8\u6b3e'), (2, '\u5f85\u53d1\u8d27'), (3, '\u5f85\u786e\u8ba4\u6536\u8d27'), (5, '\u5df2\u5b8c\u6210'), (6, '\u5df2\u5173\u95ed'), (8, '\u7ef4\u6743\u4e2d')])),
                ('receiver_name', models.CharField(max_length=64, verbose_name='\u6536\u8d27\u4eba', blank=True)),
                ('receiver_province', models.CharField(max_length=24, verbose_name='\u7701', blank=True)),
                ('receiver_city', models.CharField(max_length=24, verbose_name='\u5e02', blank=True)),
                ('receiver_zone', models.CharField(max_length=24, verbose_name='\u533a', blank=True)),
                ('receiver_address', models.CharField(max_length=128, verbose_name='\u5730\u5740', blank=True)),
                ('receiver_mobile', models.CharField(max_length=24, verbose_name='\u624b\u673a', blank=True)),
                ('receiver_phone', models.CharField(max_length=24, verbose_name='\u7535\u8bdd', blank=True)),
                ('product_id', models.CharField(max_length=64, verbose_name='\u5546\u54c1ID', blank=True)),
                ('product_name', models.CharField(max_length=64, verbose_name='\u5546\u54c1\u540d', blank=True)),
                ('product_price', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u4ef7\u683c(\u5206)')),
                ('product_sku', models.CharField(max_length=128, verbose_name='\u5546\u54c1SKU', blank=True)),
                ('product_count', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u4e2a\u6570')),
                ('product_img', models.CharField(max_length=512, verbose_name='\u5546\u54c1\u56fe\u7247', blank=True)),
                ('delivery_id', models.CharField(max_length=32, verbose_name='\u8fd0\u5355ID', blank=True)),
                ('delivery_company', models.CharField(max_length=16, verbose_name='\u7269\u6d41\u516c\u53f8\u7f16\u7801', blank=True)),
            ],
            options={
                'db_table': 'shop_weixin_order',
                'verbose_name': '\u5fae\u4fe1\u5c0f\u5e97\u8ba2\u5355',
                'verbose_name_plural': '\u5fae\u4fe1\u5c0f\u5e97\u8ba2\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXProduct',
            fields=[
                ('product_id', models.CharField(max_length=32, serialize=False, verbose_name='\u5546\u54c1ID', primary_key=True)),
                ('product_name', models.CharField(max_length=64, verbose_name='\u5546\u54c1\u6807\u9898')),
                ('product_img', models.CharField(max_length=512, verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('product_base', jsonfield.fields.JSONField(default={}, max_length=3000, verbose_name='\u56fe\u6587\u4fe1\u606f', blank=True)),
                ('sku_list', jsonfield.fields.JSONField(default={}, max_length=3000, verbose_name='\u89c4\u683c\u4fe1\u606f', blank=True)),
                ('attrext', jsonfield.fields.JSONField(default={}, max_length=1000, verbose_name='\u9644\u52a0\u4fe1\u606f', blank=True)),
                ('delivery_info', jsonfield.fields.JSONField(default={}, max_length=200, verbose_name='\u53d1\u8d27\u4fe1\u606f', blank=True)),
                ('sync_stock', models.BooleanField(default=True, verbose_name='\u540c\u6b65\u5e93\u5b58')),
                ('status', models.IntegerField(default=0, verbose_name='\u662f\u5426\u4e0a\u67b6', choices=[(1, '\u4e0a\u67b6'), (2, '\u4e0b\u67b6')])),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
            options={
                'db_table': 'shop_weixin_product',
                'verbose_name': '\u5fae\u4fe1\u5c0f\u5e97\u5546\u54c1',
                'verbose_name_plural': '\u5fae\u4fe1\u5c0f\u5e97\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXProductSku',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sku_id', models.CharField(max_length=64, verbose_name='\u89c4\u683cID')),
                ('outer_id', models.CharField(max_length=64, verbose_name='\u5546\u54c1\u7f16\u7801', blank=True)),
                ('outer_sku_id', models.CharField(max_length=64, verbose_name='\u89c4\u683c\u7f16\u7801', blank=True)),
                ('sku_name', models.CharField(max_length=64, verbose_name='\u89c4\u683c\u540d\u79f0')),
                ('sku_img', models.CharField(max_length=512, verbose_name='\u89c4\u683c\u56fe\u7247')),
                ('sku_num', models.IntegerField(default=0, verbose_name='\u89c4\u683c\u6570\u91cf')),
                ('sku_price', models.FloatField(default=0, verbose_name='\u552e\u4ef7')),
                ('ori_price', models.FloatField(default=0, verbose_name='\u539f\u4ef7')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('status', models.IntegerField(default=1, verbose_name='\u662f\u5426\u4e0a\u67b6', choices=[(1, '\u4e0a\u67b6'), (2, '\u4e0b\u67b6')])),
                ('product', models.ForeignKey(verbose_name='\u5fae\u4fe1\u5546\u54c1', to='weixin.WXProduct')),
            ],
            options={
                'db_table': 'shop_weixin_productsku',
                'verbose_name': '\u5fae\u4fe1\u5c0f\u5e97\u89c4\u683c',
                'verbose_name_plural': '\u5fae\u4fe1\u5c0f\u5e97\u89c4\u683c\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXSkuProperty',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sku_id', models.CharField(unique=True, max_length=32, verbose_name='\u89c4\u683cID')),
                ('name', models.CharField(max_length=64, verbose_name='\u89c4\u683c\u540d\u79f0')),
            ],
            options={
                'db_table': 'shop_weixin_skuproperty',
                'verbose_name': '\u5fae\u4fe1\u5546\u54c1\u5c5e\u6027',
                'verbose_name_plural': '\u5fae\u4fe1\u5546\u54c1\u5c5e\u6027\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='WXUserCharge',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wxuser_id', models.IntegerField(default=0, verbose_name='\u5fae\u4fe1\u7528\u6237ID')),
                ('status', models.CharField(default=b'effect', max_length=16, verbose_name='\u72b6\u6001', blank=True, choices=[(b'effect', '\u6709\u6548'), (b'invalid', '\u5931\u6548')])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('employee', models.ForeignKey(related_name='employee_wxusers', verbose_name='\u63a5\u7ba1\u4eba', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_weixin_user_charge',
                'verbose_name': '\u5fae\u4fe1\u7528\u6237\u63a5\u7ba1',
                'verbose_name_plural': '\u5fae\u4fe1\u7528\u6237\u63a5\u7ba1\u5217\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='weixinunionid',
            unique_together=set([('openid', 'app_key')]),
        ),
        migrations.AlterUniqueTogether(
            name='weixinlinkclicks',
            unique_together=set([('user_openid', 'link_url', 'link_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='weixinclickscorerecord',
            unique_together=set([('user_openid', 'click_score_id')]),
        ),
        migrations.AddField(
            model_name='vipcode',
            name='owner_openid',
            field=models.OneToOneField(related_name='vipcodes', verbose_name='\u5fae\u4fe1ID', to='weixin.WeiXinUser'),
        ),
        migrations.AddField(
            model_name='survey',
            name='wx_user',
            field=models.ForeignKey(related_name='surveys', verbose_name='\u5fae\u4fe1ID', to='weixin.WeiXinUser'),
        ),
        migrations.AlterUniqueTogether(
            name='invitationship',
            unique_together=set([('from_openid', 'invite_openid')]),
        ),
        migrations.AlterUniqueTogether(
            name='examuserproblem',
            unique_together=set([('user_openid', 'paper_id', 'problem_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='examuserpaper',
            unique_together=set([('user_openid', 'paper_id')]),
        ),
        migrations.AddField(
            model_name='couponclick',
            name='wx_user',
            field=models.ForeignKey(related_name='couponclicks', verbose_name='\u5fae\u4fe1ID', to='weixin.WeiXinUser'),
        ),
        migrations.AlterUniqueTogether(
            name='wxusercharge',
            unique_together=set([('wxuser_id', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='wxproductsku',
            unique_together=set([('sku_id', 'product')]),
        ),
    ]
