# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinghuo', '0049_returngoods_checked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='batch_no',
            field=models.CharField(blank=True, max_length=8, verbose_name='\u6279\u6b21\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='buy_unitprice',
            field=models.FloatField(default=0, verbose_name='\u4e70\u5165\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='\u6b64\u9879\u603b\u4ef7'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='\u4e70\u5165\u5355\u4ef7'),
        ),
    ]
