# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinghuo', '0047_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasearrangement',
            name='inbound_in',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u5df2\u5165\u4ed3'),
        ),
    ]
