# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinghuo', '0048_purchasearrangement_inbound_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='returngoods',
            name='checked_time',
            field=models.DateTimeField(null=True, verbose_name='\u5ba1\u6838\u901a\u8fc7\u65f6\u95f4'),
        )
    ]
