# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import flashsale.dinghuo.models.purchase_order


class Migration(migrations.Migration):

    dependencies = [
        ('dinghuo', '0050_add_batch_no_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='batch_no',
            field=models.CharField(blank=True, default=flashsale.dinghuo.models.purchase_order.gen_batch_no, max_length=8, unique=True, verbose_name='\u6279\u6b21\u7f16\u53f7'),
        ),
    ]
