# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinghuo', '0053_orderdetail_assign_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='type',
            field=models.IntegerField(default=0, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3')], db_index=True, default=None, null=True, verbose_name='\u6240\u5c5e\u4ed3\u5e93'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3')], default=0, verbose_name='\u6536\u8d27\u4ed3'),
        ),
    ]
