# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='user_address_unikey',
            field=models.CharField(db_index=True, help_text='\u7528\u6237\u5730\u5740sha1', max_length=40, null=True, verbose_name='\u5730\u5740\u552f\u4e00\u6807\u8bc6'),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_unikey',
            field=models.CharField(db_index=True, help_text='\u7528\u6237\u59d3\u540d\u7535\u8bddsha1', max_length=40, null=True, verbose_name='\u7528\u6237\u552f\u4e00\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.IntegerField(choices=[(0, '\u9700\u521b\u5efa\u53d1\u8d27sku\u5355'), (1, '\u5df2\u521b\u5efa\u53d1\u8d27sku\u5355'), (2, '\u5df2\u5b8c\u7ed3')], default=0, help_text='0\u672a\u5904\u74061\u53d1\u8d27\u4e2d2\u5df2\u5b8c\u7ed3', verbose_name='\u53d1\u8d27\u8fdb\u5ea6'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_flag',
            field=models.IntegerField(help_text='\u81ea\u8ba2\u8ba2\u5355\u6807\u8bb0', null=True),
        ),
    ]
