# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_auto_20161118_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realinbounddetail',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_detail_manager', to='forecast.RealInbound', verbose_name='\u5165\u4ed3\u5355'),
        ),
    ]
