# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20160615_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_method',
            field=models.IntegerField(choices=[(1, '\u652f\u4ed8\u5b9d'), (6, '\u4ee3\u4ed8'), (2, '\u8f6c\u6b3e'), (3, '\u81ea\u4ed8'), (4, '\u76f4\u9000'), (5, '\u4f59\u989d\u62b5\u6263')], verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(choices=[(-1, '\u5ef6\u671f\u5904\u7406'), (0, '\u5f85\u5904\u7406'), (1, '\u5df2\u5904\u7406'), (2, '\u5df2\u5b8c\u6210')], verbose_name='\u8d26\u5355\u72b6\u6001'),
        ),
    ]
