# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_sku_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skustock',
            name='psi_third_send_num',
            field=models.IntegerField(default=0, verbose_name='\u5f85\u4f9b\u5e94\u5546\u53d1\u8d27\u6570'),
        ),
    ]
