# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_skustock_add_third_send_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='skustock',
            name='psi_booked_num',
            field=models.IntegerField(default=0, verbose_name='\u5df2\u8ba2\u8d27\u6570'),
        ),
    ]
