# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_skustock_add_booked_num'),
    ]

    operations = [
        # migrations.AlterModelManagers(
        #     name='skustock',
        #     managers=[
        #         ('_objects', django.db.models.manager.Manager()),
        #     ],
        # ),
    ]
