# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_ware_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferiorskustats',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3'), (10, '\u8702\u5de2\u5341\u91cc\u6d0b\u573a')], db_index=True, default=1, verbose_name='\u6240\u5c5e\u4ed3\u5e93'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3'), (10, '\u8702\u5de2\u5341\u91cc\u6d0b\u573a')], db_index=True, default=1, verbose_name='\u6240\u5c5e\u4ed3\u5e93'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='outer_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='skuwarestock',
            name='ware_by',
            field=models.IntegerField(choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3'), (10, '\u8702\u5de2\u5341\u91cc\u6d0b\u573a')], db_index=True, verbose_name='\u6240\u5c5e\u4ed3\u5e93'),
        ),
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together=set([]),
        ),
    ]
