# -*- coding:utf8 -*-
__author__ = 'yann'

# 订单状态
SUBMITTING = '草稿'  # 提交中
APPROVAL = '审核'  # 审核
ZUOFEI = '作废'  # 作废
COMPLETED = '验货完成'  # 验货完成
QUESTION = '有问题'  # 有问题
DEALED = '已处理'  # 已处理

# 子订单系统内部状态
IN_EFFECT = "IN_EFFECT"
REISSUE_TYPE = 'reissue'
EXCHANGE_TYPE = 'exchange'
RETURN_GOODS_GIT_TYPE = 4  # 退货

# 系统内部状态
EMPTY_STATUS = ''
WAIT_AUDIT_STATUS = 'WAIT_AUDIT'  # 等待人工审核
WAIT_PREPARE_SEND_STATUS = 'WAIT_PREPARE_SEND'
WAIT_CHECK_BARCODE_STATUS = 'WAIT_CHECK_BARCODE'
WAIT_SCAN_WEIGHT_STATUS = 'WAIT_SCAN_WEIGHT'
FINISHED_STATUS = 'FINISHED'
INVALID_STATUS = 'INVALID'
REGULAR_REMAIN_STATUS = 'REGULAR_REMAIN'
ON_THE_FLY_STATUS = 'ON_THE_FLY'  # 合单

# 淘宝交易状态
TRADE_NO_CREATE_PAY = 'TRADE_NO_CREATE_PAY'
WAIT_BUYER_PAY = 'WAIT_BUYER_PAY'
WAIT_SELLER_SEND_GOODS = 'WAIT_SELLER_SEND_GOODS'
WAIT_BUYER_CONFIRM_GOODS = 'WAIT_BUYER_CONFIRM_GOODS'
TRADE_BUYER_SIGNED = 'TRADE_BUYER_SIGNED'
TRADE_FINISHED = 'TRADE_FINISHED'
TRADE_CLOSED = 'TRADE_CLOSED'
TRADE_CLOSED_BY_TAOBAO = 'TRADE_CLOSED_BY_TAOBAO'

# 淘宝等待卖家发货对应系统内部状态
WAIT_DELIVERY_STATUS = [WAIT_AUDIT_STATUS,
                        WAIT_PREPARE_SEND_STATUS,
                        REGULAR_REMAIN_STATUS,
                        ON_THE_FLY_STATUS]

# 交易有效的订单状态
ORDER_SUCCESS_STATUS = (WAIT_SELLER_SEND_GOODS,
                        WAIT_BUYER_CONFIRM_GOODS,
                        TRADE_BUYER_SIGNED,
                        TRADE_FINISHED)
