# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20160805_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='raised_part',
            field=models.IntegerField(blank=True, choices=[(1, '\u884c\u653f\u90e8'), (2, '\u6280\u672f\u90e8'), (3, '\u63a8\u5e7f\u90e8'), (4, '\u8d22\u52a1\u90e8'), (5, '\u5ba2\u670d\u90e8'), (6, '\u4f9b\u5e94\u94fe\u90e8'), (7, '\u4ed3\u5e93\u90e8')], verbose_name='\u63d0\u51fa\u90e8\u95e8'),
        ),
    ]
