# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0002_auto_20161212_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBoutiqueStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('model_id', models.IntegerField(verbose_name='\u6b3e\u5f0fID')),
                ('stat_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='\u4e1a\u52a1\u65e5\u671f')),
                ('model_stock_num', models.IntegerField(db_index=True, verbose_name='\u5546\u54c1\u5e93\u5b58\u6570\u91cf')),
                ('model_sale_num', models.IntegerField(db_index=True, verbose_name='\u5546\u54c1\u9500\u552e\u6570\u91cf')),
                ('model_refund_num', models.IntegerField(db_index=True, verbose_name='\u5546\u54c1\u9000\u6b3e\u6570')),
                ('coupon_sale_num', models.IntegerField(db_index=True, verbose_name='\u5238\u9500\u552e\u6570\u91cf')),
                ('coupon_use_num', models.IntegerField(db_index=True, verbose_name='\u5238\u4f7f\u7528\u6570\u91cf')),
                ('coupon_refund_num', models.IntegerField(db_index=True, verbose_name='\u9000\u5238\u6570\u91cf')),
                ('sku_stats', jsonfield.fields.JSONField(default=[], max_length=2048, verbose_name='\u89c4\u683c\u7edf\u8ba1')),
            ],
            options={
                'db_table': 'flashsale_daily_boutique_stat',
                'verbose_name': '\u7cbe\u54c1/\u6bcf\u65e5\u9500\u552e\u7edf\u8ba1',
                'verbose_name_plural': '\u7cbe\u54c1/\u6bcf\u65e5\u9500\u552e\u7edf\u8ba1\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='daystatcalcresult',
            options={'verbose_name': '\u5c0f\u9e7f\u5988\u5988/\u6570\u636e\u7edf\u8ba1\u6682\u5b58\u7ed3\u679c', 'verbose_name_plural': '\u5c0f\u9e7f\u5988\u5988/\u6570\u636e\u7edf\u8ba1\u6682\u5b58\u7ed3\u679c'},
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='total_coupon',
            field=models.IntegerField(default=0, verbose_name='\u5238\u4f7f\u7528\u989d'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyboutiquestat',
            unique_together=set([('model_id', 'stat_date')]),
        ),
    ]
