# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0003_add_daily_boutique_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySkuAmountStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('sku_id', models.IntegerField(verbose_name='\u89c4\u683cID')),
                ('model_id', models.IntegerField(db_index=True, verbose_name='\u6b3e\u5f0fID')),
                ('stat_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='\u4e1a\u52a1\u65e5\u671f')),
                ('total_amount', models.IntegerField(default=0, verbose_name='\u603b\u4ef7\u503c')),
                ('direct_payment', models.IntegerField(default=0, verbose_name='\u76f4\u63a5\u4ed8\u6b3e\u91d1\u989d')),
                ('coupon_amount', models.IntegerField(default=0, verbose_name='\u5238\u4f7f\u7528\u9762\u989d')),
                ('coupon_payment', models.IntegerField(db_index=True, default=0, verbose_name='\u5238\u5b9e\u9645\u5356\u4ef7')),
                ('exchg_amount', models.IntegerField(db_index=True, default=0, help_text='\u6263\u9664\u4e70\u5238\u91d1\u989d', verbose_name='\u5238\u5151\u6362\u51fa\u989d')),
            ],
            options={
                'db_table': 'flashsale_daily_skuamount_stat',
                'verbose_name': '\u89c4\u683cSKU/\u6bcf\u65e5\u9500\u552e\u91d1\u989d\u7edf\u8ba1',
                'verbose_name_plural': '\u89c4\u683cSKU/\u6bcf\u65e5\u9500\u552e\u91d1\u989d\u7edf\u8ba1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='DailySkuDeliveryStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('sku_id', models.IntegerField(verbose_name='\u89c4\u683cID')),
                ('model_id', models.IntegerField(db_index=True, verbose_name='\u6b3e\u5f0fID')),
                ('stat_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='\u4e1a\u52a1\u65e5\u671f')),
                ('days', models.IntegerField(db_index=True, default=0, verbose_name='\u95f4\u9694\u5929\u6570')),
                ('post_num', models.IntegerField(default=0, verbose_name='\u53d1\u8d27\u5355\u6570')),
                ('wait_num', models.IntegerField(default=0, verbose_name='\u5f85\u53d1\u5355\u6570')),
            ],
            options={
                'db_table': 'flashsale_daily_skudelivery_stat',
                'verbose_name': '\u89c4\u683cSKU/\u6bcf\u65e5\u53d1\u8d27\u72b6\u6001\u7edf\u8ba1',
                'verbose_name_plural': '\u89c4\u683cSKU/\u6bcf\u65e5\u53d1\u8d27\u72b6\u6001\u7edf\u8ba1\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='dailyboutiquestat',
            options={'verbose_name': '\u7cbe\u54c1/\u6bcf\u65e5\u9500\u552e\u6570\u91cf\u7edf\u8ba1', 'verbose_name_plural': '\u7cbe\u54c1/\u6bcf\u65e5\u9500\u552e\u6570\u91cf\u7edf\u8ba1\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='coupon_refund_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u9000\u5238\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='coupon_sale_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5238\u9500\u552e\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='coupon_use_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5238\u4f7f\u7528\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='model_refund_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5546\u54c1\u9000\u6b3e\u6570'),
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='model_sale_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5546\u54c1\u9500\u552e\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='dailyboutiquestat',
            name='model_stock_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5546\u54c1\u5e93\u5b58\u6570\u91cf'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyskudeliverystat',
            unique_together=set([('sku_id', 'stat_date', 'days')]),
        ),
        migrations.AlterUniqueTogether(
            name='dailyskuamountstat',
            unique_together=set([('sku_id', 'stat_date')]),
        ),
    ]
