# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daystats', '0006_auto_20170319_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySqlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('query_data', jsonfield.fields.JSONField(default=dict, max_length=5000, verbose_name='\u67e5\u8be2\u6761\u4ef6')),
                ('uni_key', models.CharField(max_length=32, unique=True, verbose_name='\u552f\u4e00\u6807\u8bc6')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4f7f\u7528')),
            ],
            options={
                'db_table': 'flashsale_daily_sqlrecord',
                'verbose_name': '\u6bcf\u65e5\u7edf\u8ba1/\u67e5\u8be2sql\u8bb0\u5f55',
                'verbose_name_plural': '\u6bcf\u65e5\u7edf\u8ba1/\u67e5\u8be2sql\u8bb0\u5f55',
            },
        ),
    ]
