# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20161118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='extras',
            field=jsonfield.fields.JSONField(default={}, max_length=512, verbose_name='\u9644\u52a0\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, max_length=16, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='\u624b\u673a'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='province',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u6240\u5728\u7701'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='district',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u6240\u5728\u533a/\u53bf'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='store_code',
            field=models.CharField(db_index=True, default='', help_text='\u540e\u9762\u5e94\u6539\u4e3aunique', max_length=32, verbose_name='\u4ed3\u5e93\u7f16\u7801'),
        ),
    ]
