# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_add_fields_receiver_info_to_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjust',
            name='note',
            field=models.CharField(blank=True, default='', max_length=3000, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='ware_by',
            field=models.IntegerField(blank=True, choices=[(0, '\u672a\u9009\u4ed3'), (1, '\u4e0a\u6d77\u4ed3'), (2, '\u5e7f\u5dde\u4ed3'), (3, '\u516c\u53f8\u4ed3'), (4, '\u8702\u5de2\u82cf\u5dde\u4ed3'), (5, '\u8702\u5de2\u5e7f\u5dde\u4ed3'), (9, '\u7b2c\u4e09\u65b9\u4ed3'), (10, '\u8702\u5de2\u5341\u91cc\u6d0b\u573a')], db_index=True, default=0, verbose_name='\u6240\u5c5e\u4ed3\u5e93'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
    ]
