# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0002_create_outware_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwareordersku',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True, verbose_name='\u662f\u5426\u6709\u6548'),
        ),
        migrations.AlterField(
            model_name='outwareactionrecord',
            name='state_code',
            field=models.IntegerField(choices=[(1, '\u826f\u597d'), (2, '\u51fa\u9519')], db_index=True, verbose_name='\u72b6\u6001\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='outwareinboundorder',
            name='order_type',
            field=models.IntegerField(choices=[(601, '\u91c7\u8d2d\u5165\u4ed3\u5355'), (501, '\u9500\u9000\u8d27\u5355')], db_index=True, verbose_name='\u5355\u636e\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='outwareinboundorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u65b0\u5efa'), (2, '\u63a5\u6536'), (3, '\u5230\u4ed3'), (100, '\u53d6\u6d88')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='order_type',
            field=models.IntegerField(choices=[(401, '\u9500\u552e\u8ba2\u5355'), (301, '\u9000\u4ed3\u5355')], db_index=True, verbose_name='\u5305\u88f9\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u5df2\u63a5\u5355'), (50, '\u6253\u5305\u4e2d'), (65, '\u88c5\u8f66\u4e2d'), (80, '\u5df2\u53d1\u8d27'), (100, '\u53d6\u6d88')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='union_order_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u7ec4\u5408\u8ba2\u5355\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='outwareordersku',
            name='union_order_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u5173\u8054\u7ec4\u5408\u8ba2\u5355\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='outwarepackage',
            name='package_type',
            field=models.CharField(choices=[(401, '\u9500\u552e\u8ba2\u5355'), (301, '\u9000\u4ed3\u5355')], db_index=True, max_length=16, verbose_name='\u5305\u88f9\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='outwarepackagesku',
            name='origin_skuorder_no',
            field=models.CharField(db_index=True, help_text='\u8be5\u5b57\u6bb5\u5b58\u5728\u4e89\u8bae\u6682\u4e0d\u4f7f\u7528', max_length=32, verbose_name='\u539f\u59cbSKU\u8ba2\u5355\u7f16\u53f7'),
        ),
    ]
