# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0003_add_field_skuorder_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outwareskustock',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='outwareskustock',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='outwareskustock',
            name='outware_supplier',
        ),
        migrations.RemoveField(
            model_name='outwareskustock',
            name='store_code',
        ),
        migrations.RemoveField(
            model_name='outwareskustock',
            name='uni_key',
        ),
        migrations.AddField(
            model_name='outwareskustock',
            name='adjust_num',
            field=models.IntegerField(default=0, help_text='\u8ddf\u5e93\u5b58\u8c03\u6574\u503c\u5173\u8054', verbose_name='\u8c03\u6574\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='outwareskustock',
            name='package_num',
            field=models.IntegerField(default=0, verbose_name='\u53d1\u8d27\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='outwareskustock',
            name='paid_num',
            field=models.IntegerField(default=0, verbose_name='\u4ed8\u6b3e\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='outwareskustock',
            name='refund_num',
            field=models.IntegerField(default=0, verbose_name='\u9000\u8d27\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='outwareskustock',
            name='pull_bad_qty',
            field=models.IntegerField(default=0, verbose_name='\u5916\u4ed3\u6b21\u54c1\u603b\u6570'),
        ),
        migrations.AlterField(
            model_name='outwareskustock',
            name='pull_good_available_qty',
            field=models.IntegerField(default=0, verbose_name='\u5916\u4ed3\u53ef\u5206\u914d\u826f\u54c1\u603b\u6570'),
        ),
        migrations.AlterField(
            model_name='outwareskustock',
            name='pull_good_lock_qty',
            field=models.IntegerField(default=0, verbose_name='\u5916\u4ed3\u5df2\u9501\u5b9a\u826f\u54c1\u603b\u6570'),
        ),
        migrations.AlterField(
            model_name='outwareskustock',
            name='sku_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u5185\u90e8SKU\u7f16\u53f7'),
        ),
    ]
