# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0004_change_skustock_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwaresku',
            name='is_unioned',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u540c\u6b65\u4f9b\u5e94\u5546\u4e0esku\u5173\u7cfb'),
        ),
    ]
