# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0006_outwareskustock_last_pull_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwaresku',
            name='declare_type',
            field=models.IntegerField(choices=[(0, '\u65e0\u9700\u62a5\u5173'), (10, '\u4fdd\u7a0e\u4ed3'), (20, '\u76f4\u90ae')], db_index=True, default=0, verbose_name='\u62a5\u5173\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='outwaresku',
            name='is_batch_mgt',
            field=models.BooleanField(default=False, help_text='\u652f\u6301\u6279\u6b21\u5148\u5230\u5148\u51fa', verbose_name='\u662f\u5426\u542f\u7528\u6279\u6b21\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='outwaresku',
            name='is_expire_mgt',
            field=models.BooleanField(default=False, help_text='\u652f\u6301\u5546\u54c1\u8fc7\u671f\u4e0d\u80fd\u51fa\u5355', verbose_name='\u662f\u5426\u542f\u7528\u6709\u6548\u671f\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='outwaresku',
            name='is_vendor_mgt',
            field=models.BooleanField(default=False, help_text='\u652f\u6301\u540cSKU\u591a\u4f9b\u5e94\u5546\u4f9b\u8d27', verbose_name='\u662f\u5426\u542f\u7528\u4f9b\u5e94\u5546\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='outwaresku',
            name='sku_type',
            field=models.IntegerField(choices=[(10, '\u666e\u901a\u5546\u54c1'), (20, '\u8d60\u54c1'), (30, '\u5305\u6750')], db_index=True, default=10, verbose_name='SKU\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='outwareactionrecord',
            name='action_code',
            field=models.CharField(choices=[(b'30', '\u521b\u5efa\u5546\u54c1SKU\u4fe1\u606f'), (b'31', '\u4fee\u6539\u5546\u54c1SKU\u4fe1\u606f'), (b'45', '\u5546\u54c1SKU\u4f9b\u5e94\u5546\u54c1\u5173\u8054'), (b'65', 'SKU\u5e93\u5b58\u62c9\u53d6'), (b'40', '\u521b\u5efa\u4f9b\u5e94\u5546'), (b'10', '\u521b\u5efa\u5165\u4ed3\u5355'), (b'11', '\u53d6\u6d88\u5165\u4ed3\u5355'), (b'55', '\u521b\u5efa\u9000\u4ed3\u5355'), (b'1005', '\u5165\u4ed3\u786e\u8ba4\u56de\u8c03'), (b'1006', '\u9000\u4ed3\u51fa\u5e93\u56de\u8c03'), (b'20', '\u63a8\u9001\u8ba2\u5355'), (b'21', '\u53d6\u6d88\u8ba2\u5355'), (b'23', '\u521b\u5efa\u9500\u9000\u5355'), (b'1001', '\u8ba2\u5355\u53d1\u8d27\u56de\u8c03'), (b'1002', '\u8ba2\u5355\u72b6\u6001\u53d8\u66f4\u56de\u8c03'), (b'1003', '\u9500\u9000\u5165\u5e93\u56de\u8c03'), (b'1004', '\u8ba2\u5355\u7f3a\u8d27\u56de\u8c03'), (b'150', '\u9500\u552e\u6e20\u9053\u521b\u5efa'), (b'170', '\u8de8\u5883\u63a8\u9001\u8ba2\u5355'), (b'195', '\u521b\u5efa\u8de8\u5883\u91c7\u8d2d\u5355')], db_index=True, max_length=8, verbose_name='\u64cd\u4f5c\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='outwareinboundorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u65b0\u5efa'), (2, '\u63a5\u6536'), (4, '\u5230\u4ed3'), (100, '\u53d6\u6d88')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u5df2\u63a5\u5355'), (3, '\u8ba2\u5355\u7f3a\u8d27'), (50, '\u6253\u5305\u4e2d'), (65, '\u88c5\u8f66\u4e2d'), (80, '\u5df2\u53d1\u8d27'), (100, '\u53d6\u6d88')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
