# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0007_add_mgt_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwareorder',
            name='order_source',
            field=models.IntegerField(choices=[(301, '\u9000\u4ed3\u5355'), (401, '\u9500\u552e\u8ba2\u5355')], db_index=True, default=401, verbose_name='\u8ba2\u5355\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='outwareinboundorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u672a\u63a8\u9001'), (2, '\u5df2\u63a5\u6536'), (4, '\u5df2\u5230\u4ed3'), (100, '\u5df2\u53d6\u6d88')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='order_type',
            field=models.IntegerField(choices=[(10, '\u666e\u901a\u8ba2\u5355'), (40, '\u8de8\u5883\u8ba2\u5355'), (50, '\u9884\u552e\u8ba2\u5355')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='outwaresku',
            name='is_unioned',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u540c\u6b65\u4f9b\u5e94\u5546\u4e0esku\u5173\u7cfb', verbose_name='\u5173\u8054\u4f9b\u5e94\u5546'),
        ),
    ]
