# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0008_add_wareorder_order_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outwarepackage',
            options={'verbose_name': '\u5916\u4ed3/\u51fa\u4ed3\u5305\u88f9', 'verbose_name_plural': '\u5916\u4ed3/\u51fa\u4ed3\u5305\u88f9'},
        ),
        migrations.AlterModelOptions(
            name='outwarepackagesku',
            options={'verbose_name': '\u5916\u4ed3/\u51fa\u4ed3\u5305\u88f9sku', 'verbose_name_plural': '\u5916\u4ed3/\u51fa\u4ed3\u5305\u88f9sku'},
        ),
        migrations.AddField(
            model_name='outwareaccount',
            name='order_prefix',
            field=models.CharField(blank=True, default='test_', max_length=8, verbose_name='\u8ba2\u5355\u524d\u7f00'),
        ),
        migrations.AddField(
            model_name='outwareaccount',
            name='ware_from',
            field=models.CharField(blank=True, choices=[('fengchao', '\u8702\u5de2'), ('wdt', '\u65fa\u5e97\u901a')], max_length=16, verbose_name='\u4f9b\u5e94\u94fe\u63d0\u4f9b\u65b9'),
        ),
        migrations.AlterField(
            model_name='outwareaccount',
            name='extras',
            field=jsonfield.fields.JSONField(default={}, max_length=1024, verbose_name='\u9644\u52a0\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='outwarepackage',
            name='package_type',
            field=models.IntegerField(choices=[(401, '\u9500\u552e\u8ba2\u5355'), (301, '\u9000\u4ed3\u5355')], db_index=True, verbose_name='\u5305\u88f9\u7c7b\u578b'),
        ),
    ]
