# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0009_add_ware_from_and_order_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwareorder',
            name='state',
            field=models.IntegerField(choices=[(1, '\u5f85\u5904\u7406'), (20, '\u5df2\u5ba1\u6838'), (25, '\u88c5\u8f66\u4e2d'), (26, '\u5df2\u53d1\u8d27'), (30, '\u53d6\u6d88'), (35, '\u6253\u5305\u4e2d'), (40, '\u88c5\u8f66\u4e2d'), (60, '\u5df2\u53d1\u8d27'), (65, '\u53d6\u6d88'), (70, '\u6253\u5305\u4e2d'), (80, '\u88c5\u8f66\u4e2d'), (100, '\u5df2\u53d1\u8d27'), (201, '\u8702\u5de2\u5ba1\u6838\u672a\u901a\u8fc7'), (202, '\u76f4\u53d1\u8f6c\u53d1\u5931\u8d25')], default=1, verbose_name='\u5916\u4ed3\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='outwareorder',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '\u5f85\u63a8\u9001'), (2, '\u5df2\u63a5\u5355'), (3, '\u8ba2\u5355\u7f3a\u8d27'), (4, '\u5df2\u5230\u8d27')], db_index=True, default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
