# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FengchaoOrderChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('channel_id', models.CharField(max_length=16, unique=True, verbose_name='\u9500\u552e\u6e20\u9053 ID')),
                ('channel_name', models.CharField(db_index=True, max_length=16, verbose_name='\u9500\u552e\u6e20\u9053\u540d\u5b57')),
                ('channel_type', models.CharField(choices=[('1', '\u6dd8\u5b9d'), ('2', '\u5929\u732b'), ('7', '\u4eac\u4e1c\u5546\u57ce'), ('11', '\u4e9a\u9a6c\u900a'), ('12', '\u4e00\u53f7\u5e97'), ('13', '\u56fd\u7f8e\u5546\u57ce'), ('14', '\u82cf\u5b81'), ('15', '\u963f\u91cc\u5df4\u5df4'), ('16', '\u5f53\u5f53\u7f51'), ('17', 'eBay'), ('18', '\u552f\u54c1\u4f1a'), ('19', '\u805a\u7f8e\u4f18\u54c1'), ('20', '\u81ea\u6709\u5546\u57ce'), ('32', '\u871c\u82bd'), ('33', 'JD\u5168\u7403\u552e')], db_index=True, max_length=16, verbose_name='\u6e20\u9053\u7c7b\u578b')),
                ('channel_client_id', models.CharField(db_index=True, max_length=16, verbose_name='\u9500\u552e\u6e20\u9053\u5546\u5bb6\u4ee3\u7801')),
                ('status', models.BooleanField(default=False, verbose_name='\u66f4\u65b0\u72b6\u6001')),
                ('extras', jsonfield.fields.JSONField(default={}, max_length=512, verbose_name='\u9644\u52a0\u4fe1\u606f')),
            ],
            options={
                'db_table': 'fengchao_orderchannnel',
                'verbose_name': '\u5916\u4ed3/\u8702\u5de2\u8ba2\u5355\u6765\u6e90\u6e20\u9053',
                'verbose_name_plural': '\u5916\u4ed3/\u8702\u5de2\u8ba2\u5355\u6765\u6e90\u6e20\u9053',
            },
        ),
    ]
