# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0024_create_table_shop_trades_erp_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erporder',
            name='delivery_time',
            field=models.DateTimeField(null=True, verbose_name='\u53d1\u8d27\u65f6\u95f4'),
        ),
    ]
