# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0027_auto_20161118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageskuitem',
            name='init_assigned',
            field=models.BooleanField(default=False, verbose_name='\u521d\u59cb\u5373\u5206\u914d'),
        ),
        migrations.AddField(
            model_name='packageskuitem',
            name='is_boutique',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7cbe\u54c1\u8ba2\u5355'),
        )
    ]
