# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20161120_1200'),
        ('trades', '0028_psi_init_assigned'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='packageskuitem',
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='packageorder',
            name='action_type',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u53d1\u8d27'), (1, '\u7279\u6b8a\u53d1\u8d27')], default=0, help_text='\u53d1\u8d27\u7c7b\u578b\u6307\u5b9a\u4ed3\u5e93\u67e5\u770b\u5230\u5305\u88f9\u540e\u8fdb\u884c\u7684\u52a8\u4f5c', verbose_name='\u53d1\u8d27\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4f9b\u5e94\u5546id'),
        ),
        migrations.AddField(
            model_name='packageskuitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='packageskuitem',
            name='type',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u8ba2\u5355'), (1, '\u624b\u5de5\u53d1\u4ef6'), (2, '\u6e05\u5e93\u5b58'), (3, '\u9000\u591a\u8d27'), (4, '\u9000\u6b21\u54c1'), (5, '\u5929\u732b\u5546\u57ce\u5355')], default=0, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u91c7\u8d2d\u5458'),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='tid',
            field=models.CharField(max_length=32, verbose_name='\u9000\u8d27\u5355\u53f7|\u53c2\u8003\u4ea4\u6613\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='packageskuitem',
            name='oid',
            field=models.CharField(db_index=True, max_length=40, null=True, verbose_name='SKU\u4ea4\u6613\u5355\u53f7|\u9000\u8d27\u8be6\u5355ID'),
        ),
        migrations.AlterField(
            model_name='packageskuitem',
            name='pay_time',
            field=models.DateTimeField(db_index=True, verbose_name='\u786e\u8ba4\u8981\u53d1\u65f6\u95f4\uff08\u4ed8\u6b3e\u65f6\u95f4|\u5929\u732b\u6210\u4ea4\u65f6\u95f4|\u9000\u8d27\u5ba1\u6838\u65f6\u95f4|\u8be5\u65f6\u95f4\u51b3\u5b9a\u53d1\u8d27\u987a\u5e8f\uff09'),
        ),
        migrations.AlterField(
            model_name='packageskuitem',
            name='sale_order_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='SKU\u8ba2\u5355ID'),
        ),
        migrations.AlterField(
            model_name='packageskuitem',
            name='sale_trade_id',
            field=models.CharField(db_index=True, max_length=40, null=True, verbose_name='\u4ea4\u6613\u5355\u53f7|\u9000\u8d27\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='returnwuliu',
            name='status',
            field=models.IntegerField(choices=[(0, '\u67e5\u8be2\u5f02\u5e38'), (1, '\u5feb\u9012100\u4e0b\u7684\u67e5\u8be2\u7ed3\u679c'), (2, '\u5728\u9014\u4e2d'), (3, '\u7b7e\u6536'), (4, '\u95ee\u9898\u4ef6')], db_index=True, default=0, verbose_name='\u7269\u6d41\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='tradewuliu',
            name='status',
            field=models.IntegerField(choices=[(0, '\u67e5\u8be2\u5f02\u5e38'), (1, '\u5feb\u9012100\u4e0b\u7684\u67e5\u8be2\u7ed3\u679c'), (2, '\u5728\u9014\u4e2d'), (3, '\u7b7e\u6536'), (4, '\u95ee\u9898\u4ef6')], db_index=True, default=0, verbose_name='\u7269\u6d41\u72b6\u6001'),
        ),
    ]
