# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0029_psi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='purchaser',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u91c7\u8d2d\u5458'),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='buyer_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='\u4e70\u5bb6ID'),
        ),
    ]
