# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0030_psi_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='action_type',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u53d1\u8d27'), (1, '\u7279\u6b8a\u53d1\u8d27')], db_index=True, default=0, help_text='\u53d1\u8d27\u7c7b\u578b\u6307\u5b9a\u4ed3\u5e93\u67e5\u770b\u5230\u5305\u88f9\u540e\u8fdb\u884c\u7684\u52a8\u4f5c', verbose_name='\u53d1\u8d27\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='packageskuitem',
            name='type',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u8ba2\u5355'), (1, '\u624b\u5de5\u53d1\u4ef6'), (2, '\u6e05\u5e93\u5b58'), (3, '\u9000\u591a\u8d27'), (4, '\u9000\u6b21\u54c1'), (5, '\u5929\u732b\u5546\u57ce\u5355')], db_index=True, default=0, verbose_name='\u7c7b\u578b'),
        )
    ]
