# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0031_pkg_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='user_address_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='\u5730\u5740ID'),
        )
    ]
