# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0032_pkg_user_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageskuitem',
            name='note_recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packageskuitem', to=settings.AUTH_USER_MODEL, verbose_name='\u5907\u6ce8\u8bb0\u5f55\u4eba'),
        ),
    ]
