# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0010_auto_20161118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixinaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u516c\u4f17\u53f7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='weixinaccount',
            name='account_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u539f\u59cbID'),
        ),
    ]
