# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JimayAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='\u6635\u79f0')),
                ('name', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='\u59d3\u540d')),
                ('idcard_no', models.CharField(blank=True, max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('weixin', models.CharField(blank=True, db_index=True, max_length=24, verbose_name='\u5fae\u4fe1')),
                ('mobile', models.CharField(blank=True, max_length=11, unique=True, verbose_name='\u624b\u673a')),
                ('level', models.IntegerField(db_index=True, default=0, verbose_name='\u7ea7\u522b')),
                ('parent_agent_id', models.IntegerField(db_index=True, default=0, verbose_name='\u7236\u7ea7\u4ee3\u7406ID')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u6536\u8d27\u5730\u5740')),
                ('certification', models.CharField(blank=True, max_length=256, verbose_name='\u8bc1\u4e66\u5730\u5740')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
            options={
                'db_table': 'jimay_agent',
                'verbose_name': '\u5df1\u7f8e\u533b\u5b66/\u7279\u7ea6\u4ee3\u7406',
                'verbose_name_plural': '\u5df1\u7f8e\u533b\u5b66/\u7279\u7ea6\u4ee3\u7406',
            },
        ),
    ]
