# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_logisticscompany_type'),
        ('jimay', '0003_add_pic_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jimayagentorder',
            name='logistic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.LogisticsCompany', verbose_name='\u7269\u6d41\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='jimayagentorder',
            name='logistic_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u7269\u6d41\u5355\u53f7'),
        ),
    ]
