# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimay', '0005_add_jimay_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='jimayagentorder',
            name='sys_memo',
            field=models.CharField(blank=True, max_length=512, verbose_name='\u7cfb\u7edf\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='jimayagent',
            name='level',
            field=models.IntegerField(choices=[(3, '\u603b\u4ee3'), (2, '\u7701\u4ee3'), (1, '\u5e02\u4ee3'), (0, '\u7279\u7ea6')], db_index=True, default=0, verbose_name='\u7ea7\u522b'),
        ),
    ]
