# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jimay', '0006_add_sys_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JimayAgentStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_invite_num', models.IntegerField(default=0, verbose_name='\u76f4\u63a5\u53d1\u5c55\u4ee3\u7406\u6570\u91cf')),
                ('indirect_invite_num', models.IntegerField(default=0, help_text='\u6240\u6709\u4e0b\u7ea7\u4ee3\u7406\u7684\u53d1\u5c55\u7684\u603b\u4eba\u6570', verbose_name='\u95f4\u63a5\u53d1\u5c55\u4ee3\u7406\u6570\u91cf')),
                ('direct_sales', models.IntegerField(default=0, help_text='\u81ea\u5df1\u4e0b\u5355\u7684\u91d1\u989d', verbose_name='\u76f4\u63a5\u9500\u552e\u989d')),
                ('indirect_sales', models.IntegerField(default=0, help_text='\u6240\u6709\u4e0b\u7ea7\u4ee3\u7406\u4e0b\u5355\u7684\u603b\u91d1\u989d', verbose_name='\u95f4\u63a5\u9500\u552e\u989d')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_stat', to='jimay.JimayAgent', verbose_name='\u5df1\u7f8e\u4ee3\u7406')),
            ],
            options={
                'db_table': 'jimay_agentstat',
                'verbose_name': '\u5df1\u7f8e\u533b\u5b66/\u8fd0\u8425\u7edf\u8ba1',
                'verbose_name_plural': '\u5df1\u7f8e\u533b\u5b66/\u8fd0\u8425\u7edf\u8ba1',
            },
        ),
        migrations.AlterField(
            model_name='jimayagentorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jimay_agent_manager', to='pay.UserAddress', verbose_name='\u7528\u6237\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='jimayagentorder',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5df2\u63d0\u4ea4\u7533\u8bf7'), (1, '\u5df2\u786e\u8ba4\u8ba2\u91d1'), (2, '\u5df2\u786e\u8ba4\u4ed8\u6b3e'), (3, '\u5df2\u6253\u5305\u51fa\u5e93'), (4, '\u5df2\u7b7e\u6536\u5b8c\u6210'), (5, '\u5df2\u53d6\u6d88\u8ba2\u8d27')], db_index=True, default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
