# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimay', '0007_create_agent_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='jimayagent',
            name='is_graduated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u7ed3\u4e1a'),
        ),
        migrations.AddField(
            model_name='jimayagent',
            name='time_graduated_en',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u7ed3\u4e1a\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='jimayagent',
            name='time_graduated_st',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u4e0a\u8bfe\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='jimayagentorder',
            name='payment',
            field=models.IntegerField(default=0, help_text='\u73b0\u9ed8\u8ba4\u7531\u8fd0\u8425\u4eba\u5458\u586b\u5199', verbose_name='\u652f\u4ed8\u91d1\u989d(\u5206)'),
        ),
        migrations.AlterField(
            model_name='jimayagentorder',
            name='total_fee',
            field=models.IntegerField(default=0, help_text='\u5546\u54c1\u96f6\u552e\u4ef7', verbose_name='\u5546\u54c1\u603b\u4ef7(\u5206)'),
        ),
    ]
