# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimay', '0008_add_graduated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jimayagentorder',
            name='channel',
            field=models.IntegerField(choices=[(1, '\u4e2a\u4eba\u5fae\u4fe1'), (2, '\u4e2a\u4eba\u652f\u4ed8\u5b9d'), (3, '\u94f6\u884c\u8f6c\u8d26')], db_index=True, default=0, verbose_name='\u652f\u4ed8\u6e20\u9053'),
        ),
    ]
