# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outware', '0005_outwaresku_is_unioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwareskustock',
            name='last_pull_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='\u5e93\u5b58\u6700\u540e\u66f4\u65b0\u65e5\u671f'),
        ),
    ]
