# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0016_xlmmdailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_time', models.DateTimeField(auto_now=True)),
                ('stat_sku_cnt', models.IntegerField(default=0)),
                ('err_skus', jsonfield.fields.JSONField(default=[], max_length=10000, verbose_name='\u51fa\u9519sku\u5217\u8868')),
            ],
            options={
                'db_table': 'stat_stockdailyreport',
            },
        ),
        migrations.CreateModel(
            name='StockDailyReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField()),
                ('sys_data', jsonfield.fields.JSONField(default=dict, max_length=5000, verbose_name='\u7cfb\u7edfsku\u6570\u636e')),
                ('stat_data', jsonfield.fields.JSONField(default=dict, max_length=5000, verbose_name='\u7edf\u8ba1sku\u6570\u636e')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.StockDailyReport')),
            ],
            options={
                'db_table': 'stat_stockdailyreportitem',
            },
        ),
    ]
