# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0068_xiaolumama_elite_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamamission',
            name='is_push_msg',
            field=models.BooleanField(default=True, verbose_name='\u63a8\u9001\u6d88\u606f'),
        ),
        migrations.AlterField(
            model_name='envelop',
            name='send_status',
            field=models.CharField(choices=[('unsend', '\u5f85\u53d1\u653e'), ('sending', '\u53d1\u653e\u4e2d'), ('sent', '\u5df2\u53d1\u653e\u5f85\u9886\u53d6'), ('failed', '\u53d1\u653e\u5931\u8d25'), ('received', '\u5df2\u9886\u53d6'), ('refund', '\u5df2\u9000\u6b3e')], db_index=True, default='unsend', max_length=8, verbose_name='\u53d1\u9001\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='mamadailytabvisit',
            name='stats_tab',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, '\u5988\u5988\u4e3b\u9875'), (2, '\u6bcf\u65e5\u63a8\u9001'), (3, '\u6d88\u606f\u901a\u77e5'), (4, '\u5e97\u94fa\u7cbe\u9009'), (5, '\u9080\u8bf7\u5988\u5988'), (6, '\u9009\u54c1\u4f63\u91d1'), (7, 'VIP\u8003\u8bd5'), (8, '\u5988\u5988\u56e2\u961f'), (9, '\u6536\u76ca\u6392\u540d'), (10, '\u8ba2\u5355\u8bb0\u5f55'), (11, '\u6536\u76ca\u8bb0\u5f55'), (12, '\u7c89\u4e1d\u5217\u8868'), (13, '\u8bbf\u5ba2\u5217\u8868'), (14, 'WX/\u5e97\u94fa\u6fc0\u6d3b'), (15, 'WX/APP\u4e0b\u8f7d'), (16, 'WX/\u5f00\u5e97\u4e8c\u7ef4\u7801'), (17, 'WX/\u7ba1\u7406\u5458\u4e8c\u7ef4\u7801'), (18, 'WX/\u5ba2\u670d\u83dc\u5355'), (19, 'WX/\u4e2a\u4eba\u5e10\u6237'), (20, 'WX/\u63d0\u73b0\u9875APP\u4e0b\u8f7d'), (21, 'WX/\u8df3\u8f6c\u4e13\u9898\u94fe\u63a5'), (22, 'WX/\u8df3\u8f6c\u5fae\u4fe1\u6587\u7ae0'), (23, 'WX/\u65b0\u624b\u6559\u7a0b'), (24, 'WX/\u7ed1\u5b9a\u624b\u673a'), (25, 'WX/\u70b9\u51fb\u6536\u76ca\u63a8\u9001'), (26, 'WX/\u70b9\u51fb\u8fd4\u73b0\u8bf4\u660e'), (27, 'APP/\u7cbe\u82f1\u5988\u5988'), (28, 'WX/\u65b0\u5988\u5988\u63a8\u9001'), (29, 'WX/\u5e7f\u544a'), (30, '\u7cbe\u54c1\u6c47')], db_index=True, default=0, verbose_name='\u529f\u80fdTAB'),
        ),
        migrations.AlterField(
            model_name='mamasalegrade',
            name='grade',
            field=models.IntegerField(choices=[(30000, 'A'), (60000, 'B'), (90000, 'C'), (120000, 'D'), (150000, 'E'), (180000, 'F'), (210000, 'G')], db_index=True, default=0, verbose_name='\u9500\u552e\u7ea7\u522b'),
        ),
        migrations.AlterField(
            model_name='mamatabvisitstats',
            name='stats_tab',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, '\u5988\u5988\u4e3b\u9875'), (2, '\u6bcf\u65e5\u63a8\u9001'), (3, '\u6d88\u606f\u901a\u77e5'), (4, '\u5e97\u94fa\u7cbe\u9009'), (5, '\u9080\u8bf7\u5988\u5988'), (6, '\u9009\u54c1\u4f63\u91d1'), (7, 'VIP\u8003\u8bd5'), (8, '\u5988\u5988\u56e2\u961f'), (9, '\u6536\u76ca\u6392\u540d'), (10, '\u8ba2\u5355\u8bb0\u5f55'), (11, '\u6536\u76ca\u8bb0\u5f55'), (12, '\u7c89\u4e1d\u5217\u8868'), (13, '\u8bbf\u5ba2\u5217\u8868'), (14, 'WX/\u5e97\u94fa\u6fc0\u6d3b'), (15, 'WX/APP\u4e0b\u8f7d'), (16, 'WX/\u5f00\u5e97\u4e8c\u7ef4\u7801'), (17, 'WX/\u7ba1\u7406\u5458\u4e8c\u7ef4\u7801'), (18, 'WX/\u5ba2\u670d\u83dc\u5355'), (19, 'WX/\u4e2a\u4eba\u5e10\u6237'), (20, 'WX/\u63d0\u73b0\u9875APP\u4e0b\u8f7d'), (21, 'WX/\u8df3\u8f6c\u4e13\u9898\u94fe\u63a5'), (22, 'WX/\u8df3\u8f6c\u5fae\u4fe1\u6587\u7ae0'), (23, 'WX/\u65b0\u624b\u6559\u7a0b'), (24, 'WX/\u7ed1\u5b9a\u624b\u673a'), (25, 'WX/\u70b9\u51fb\u6536\u76ca\u63a8\u9001'), (26, 'WX/\u70b9\u51fb\u8fd4\u73b0\u8bf4\u660e'), (27, 'APP/\u7cbe\u82f1\u5988\u5988'), (28, 'WX/\u65b0\u5988\u5988\u63a8\u9001'), (29, 'WX/\u5e7f\u544a'), (30, '\u7cbe\u54c1\u6c47')], db_index=True, default=0, verbose_name='\u529f\u80fdTAB'),
        ),
    ]
