# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0070_auto_20161219_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MamaReferalTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('referal_to_mama_id', models.IntegerField(default=0, unique=True, verbose_name='\u5c0f\u9e7f\u5988\u5988id')),
                ('referal_from_mama_id', models.IntegerField(db_index=True, default=0, verbose_name='\u4e0a\u7ea7\u5988\u5988id')),
                ('direct_invite_num', models.IntegerField(db_index=True, default=0, verbose_name='\u76f4\u63a5\u9080\u8bf7\u6570')),
                ('indirect_invite_num', models.IntegerField(db_index=True, default=0, verbose_name='\u95f4\u63a5\u9080\u8bf7\u6570')),
                ('gradient', models.IntegerField(db_index=True, default=0, verbose_name='\u68af\u5ea6')),
                ('is_elite', models.BooleanField(db_index=True, default=True, verbose_name='\u7cbe\u82f1\u5988\u5988')),
                ('last_active_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u6700\u8fd1\u6d3b\u8dc3\u65f6\u95f4')),
            ],
            options={
                'db_table': 'flashsale_xlmm_referaltree',
                'verbose_name': 'V2/\u5988\u5988\u6811\u5f62\u5173\u7cfb\u6570\u636e',
                'verbose_name_plural': 'V2/\u5988\u5988\u6811\u5f62\u5173\u7cfb\u6570\u636e\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='mamadailytabvisit',
            name='stats_tab',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, '\u5988\u5988\u4e3b\u9875'), (2, '\u6bcf\u65e5\u63a8\u9001'), (3, '\u6d88\u606f\u901a\u77e5'), (4, '\u5e97\u94fa\u7cbe\u9009'), (5, '\u9080\u8bf7\u5988\u5988'), (6, '\u9009\u54c1\u4f63\u91d1'), (7, 'VIP\u8003\u8bd5'), (8, '\u5988\u5988\u56e2\u961f'), (9, '\u6536\u76ca\u6392\u540d'), (10, '\u8ba2\u5355\u8bb0\u5f55'), (11, '\u6536\u76ca\u8bb0\u5f55'), (12, '\u7c89\u4e1d\u5217\u8868'), (13, '\u8bbf\u5ba2\u5217\u8868'), (14, 'WX/\u5e97\u94fa\u6fc0\u6d3b'), (15, 'WX/APP\u4e0b\u8f7d'), (16, 'WX/\u5f00\u5e97\u4e8c\u7ef4\u7801'), (17, 'WX/\u7ba1\u7406\u5458\u4e8c\u7ef4\u7801'), (18, 'WX/\u5ba2\u670d\u83dc\u5355'), (19, 'WX/\u4e2a\u4eba\u5e10\u6237'), (20, 'WX/\u63d0\u73b0\u9875APP\u4e0b\u8f7d'), (21, 'WX/\u8df3\u8f6c\u4e13\u9898\u94fe\u63a5'), (22, 'WX/\u8df3\u8f6c\u5fae\u4fe1\u6587\u7ae0'), (23, 'WX/\u65b0\u624b\u6559\u7a0b'), (24, 'WX/\u7ed1\u5b9a\u624b\u673a'), (25, 'WX/\u70b9\u51fb\u6536\u76ca\u63a8\u9001'), (26, 'WX/\u70b9\u51fb\u8fd4\u73b0\u8bf4\u660e'), (27, 'APP/\u7cbe\u82f1\u5988\u5988'), (28, 'WX/\u65b0\u5988\u5988\u63a8\u9001'), (29, 'WX/\u5e7f\u544a'), (30, '\u7cbe\u54c1\u6c47'), (31, '\u7cbe\u54c1\u6c47\u54a8\u8be2')], db_index=True, default=0, verbose_name='\u529f\u80fdTAB'),
        ),
        migrations.AlterField(
            model_name='mamatabvisitstats',
            name='stats_tab',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, '\u5988\u5988\u4e3b\u9875'), (2, '\u6bcf\u65e5\u63a8\u9001'), (3, '\u6d88\u606f\u901a\u77e5'), (4, '\u5e97\u94fa\u7cbe\u9009'), (5, '\u9080\u8bf7\u5988\u5988'), (6, '\u9009\u54c1\u4f63\u91d1'), (7, 'VIP\u8003\u8bd5'), (8, '\u5988\u5988\u56e2\u961f'), (9, '\u6536\u76ca\u6392\u540d'), (10, '\u8ba2\u5355\u8bb0\u5f55'), (11, '\u6536\u76ca\u8bb0\u5f55'), (12, '\u7c89\u4e1d\u5217\u8868'), (13, '\u8bbf\u5ba2\u5217\u8868'), (14, 'WX/\u5e97\u94fa\u6fc0\u6d3b'), (15, 'WX/APP\u4e0b\u8f7d'), (16, 'WX/\u5f00\u5e97\u4e8c\u7ef4\u7801'), (17, 'WX/\u7ba1\u7406\u5458\u4e8c\u7ef4\u7801'), (18, 'WX/\u5ba2\u670d\u83dc\u5355'), (19, 'WX/\u4e2a\u4eba\u5e10\u6237'), (20, 'WX/\u63d0\u73b0\u9875APP\u4e0b\u8f7d'), (21, 'WX/\u8df3\u8f6c\u4e13\u9898\u94fe\u63a5'), (22, 'WX/\u8df3\u8f6c\u5fae\u4fe1\u6587\u7ae0'), (23, 'WX/\u65b0\u624b\u6559\u7a0b'), (24, 'WX/\u7ed1\u5b9a\u624b\u673a'), (25, 'WX/\u70b9\u51fb\u6536\u76ca\u63a8\u9001'), (26, 'WX/\u70b9\u51fb\u8fd4\u73b0\u8bf4\u660e'), (27, 'APP/\u7cbe\u82f1\u5988\u5988'), (28, 'WX/\u65b0\u5988\u5988\u63a8\u9001'), (29, 'WX/\u5e7f\u544a'), (30, '\u7cbe\u54c1\u6c47'), (31, '\u7cbe\u54c1\u6c47\u54a8\u8be2')], db_index=True, default=0, verbose_name='\u529f\u80fdTAB'),
        ),
        migrations.AlterField(
            model_name='xiaolumama',
            name='referal_from',
            field=models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('INDIRECT', 'INDIRECT')], db_index=True, max_length=11, verbose_name='\u7cbe\u82f1\u5988\u5988\u7c7b\u578b'),
        ),
    ]
