# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0071_auto_20170104_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamareferaltree',
            name='is_vip',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u4ed8\u8d39\u5988\u5988'),
        ),
        migrations.AlterField(
            model_name='mamareferaltree',
            name='is_elite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7cbe\u82f1\u5988\u5988'),
        ),
    ]
