# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0072_auto_20170104_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteMamaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('mama_id', models.IntegerField(unique=True, verbose_name='\u5988\u5988ID')),
                ('sub_mamacount', models.IntegerField(db_index=True, default=0, verbose_name='\u4e0b\u7ea7\u6570\u91cf')),
                ('purchase_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u8fdb\u8d27\u91d1\u989d')),
                ('transfer_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u8f6c\u7ed9\u4e0b\u5c5e')),
                ('return_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u4e0b\u5c5e\u9000\u8fd8')),
                ('sale_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u4e70\u8d27\u91d1\u989d')),
                ('exchg_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u5151\u5238\u91d1\u989d')),
                ('refund_amount', models.IntegerField(db_index=True, default=0, verbose_name='\u9000\u5238\u91d1\u989d')),
                ('saleout_rate', models.FloatField(db_index=True, default=0, verbose_name='\u51fa\u8d27\u7387')),
                ('transfer_rate', models.FloatField(db_index=True, default=0, help_text='\u5238\u8f6c\u79fb\u7ed9\u4e0b\u5c5e\u6bd4\u4f8b', verbose_name='\u6d41\u901a\u7387')),
                ('refund_rate', models.FloatField(db_index=True, default=0, verbose_name='\u9000\u5238\u7387')),
                ('joined_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('last_active_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='\u6700\u8fd1\u6d3b\u8dc3\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5f85\u8ddf\u8fdb'), (2, '\u8ddf\u8fdb\u4e2d')], db_index=True, default=0, verbose_name='\u72b6\u6001')),
                ('memo', models.TextField(max_length=1024, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'xiaolumm_elitestatus',
                'verbose_name': '\u7cbe\u82f1\u5988\u5988/\u6d3b\u8dc3\u72b6\u6001',
                'verbose_name_plural': '\u7cbe\u82f1\u5988\u5988/\u6d3b\u8dc3\u72b6\u6001\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='carryrecord',
            name='carry_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u76ca\u6570(\u5206)'),
        ),
    ]
