# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0073_create_model_elitemama_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='exchg_amount',
        ),
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='purchase_amount',
        ),
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='return_amount',
        ),
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='sale_amount',
        ),
        migrations.RemoveField(
            model_name='elitemamastatus',
            name='transfer_amount',
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='exchg_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5151\u6362\u51fa\u8d27\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='exchg_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u5151\u6362\u4e70\u8d27\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='purchase_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u8fdb\u5238\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='purchase_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u51fa\u5238\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='refund_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u56de\u5238\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='refund_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u9000\u5238\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='return_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u6536\u56de\u4e0b\u7ea7\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='return_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u9000\u8fd8\u4e0a\u7ea7\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='sale_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u76f4\u63a5\u51fa\u8d27\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='sale_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u76f4\u63a5\u4e70\u8d27\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='transfer_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u8f6c\u5165\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='transfer_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u8f6c\u51fa\u9762\u989d'),
        ),
        migrations.AlterField(
            model_name='elitemamastatus',
            name='sub_mamacount',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u4e0b\u5c5e\u6570\u91cf'),
        ),
    ]
