# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0073_create_model_elitemama_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='XiaoluCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('mama_id', models.IntegerField(db_index=True, default=0, verbose_name='\u5988\u5988\u7f16\u53f7')),
                ('amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d(\u5206)')),
            ],
            options={
                'db_table': 'flashsale_xlmm_xiaolucoin',
                'verbose_name': '\u5c0f\u9e7f\u5e01',
                'verbose_name_plural': '\u5c0f\u9e7f\u5e01',
            },
        ),
        migrations.CreateModel(
            name='XiaoluCoinLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('mama_id', models.IntegerField(db_index=True, default=0, verbose_name='\u5988\u5988\u7f16\u53f7')),
                ('iro_type', models.CharField(choices=[('in', '\u6536\u5165'), ('out', '\u652f\u51fa')], max_length=4, verbose_name='\u6536\u652f\u7c7b\u578b')),
                ('amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d(\u5206)')),
                ('subject', models.CharField(choices=[('chongzhi', '\u5145\u503c'), ('consume', '\u6d88\u8d39'), ('refund', '\u9000\u6b3e')], db_index=True, max_length=16, verbose_name='\u8bb0\u5f55\u7c7b\u578b')),
                ('date_field', models.DateField(default=datetime.date.today, verbose_name='\u4e1a\u52a1\u65e5\u671f')),
                ('referal_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='\u5f15\u7528id')),
                ('uni_key', models.CharField(max_length=128, null=True, unique=True, verbose_name='\u552f\u4e00ID')),
            ],
            options={
                'db_table': 'flashsale_xlmm_xiaolucoinlog',
                'verbose_name': '\u5c0f\u9e7f\u5e01\u6536\u652f\u8bb0\u5f55',
                'verbose_name_plural': '\u5c0f\u9e7f\u5e01\u6536\u652f\u8bb0\u5f55',
            },
        ),
    ]
