# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0074_alter_fields_elitemama_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elitemamastatus',
            name='gift_amount_in',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u8d60\u5165\u9762\u989d'),
        ),
        migrations.AddField(
            model_name='elitemamastatus',
            name='gift_amount_out',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u8d60\u51fa\u9762\u989d'),
        ),
    ]
