# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0077_create_flashsale_xlmm_xiaolucoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elitemamastatus',
            name='transfer_rate',
            field=models.FloatField(db_index=True, default=0, help_text='\u5238\u8f6c\u79fb\u7ed9\u4e0b\u5c5e\u6bd4\u4f8b', verbose_name='\u8f6c\u79fb\u6d41\u901a\u7387'),
        ),
        migrations.AlterField(
            model_name='xiaolucoinlog',
            name='subject',
            field=models.CharField(choices=[('recharge', '\u5145\u503c'), ('consume', '\u6d88\u8d39'), ('refund', '\u9000\u6b3e')], db_index=True, max_length=16, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='xiaolumama',
            name='last_renew_type',
            field=models.IntegerField(choices=[(3, '\u8bd5\u75283'), (15, '\u8bd5\u752815'), (90, '\u7cbe\u82f1mama'), (183, '\u534a\u5e74'), (365, '\u4e00\u5e74')], db_index=True, default=3, verbose_name='\u6700\u8fd1\u7eed\u8d39\u7c7b\u578b'),
        ),
    ]
