# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0078_alert_fileds_change_xlmm_renewtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamareferaltree',
            name='direct_fans_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u76f4\u63a5\u7c89\u4e1d\u6570'),
        ),
        migrations.AddField(
            model_name='mamareferaltree',
            name='fans_gradient',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u7c89\u4e1d\u68af\u5ea6'),
        ),
        migrations.AddField(
            model_name='mamareferaltree',
            name='indirect_fans_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u95f4\u63a5\u7c89\u4e1d\u6570'),
        ),
        migrations.AlterField(
            model_name='mamareferaltree',
            name='gradient',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u9080\u8bf7\u68af\u5ea6'),
        ),
    ]
