# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0079_add_fans_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('customer_id', models.IntegerField(default=0, verbose_name='\u7528\u6237ID')),
                ('amount', models.IntegerField(default=0, verbose_name='\u91d1\u989d(\u5206)')),
                ('obj_id', models.CharField(db_index=True, help_text='\u4e24\u6761double entry\u7eaa\u5f55\u7684\u503c\u5fc5\u987b\u76f8\u540c', max_length=64, verbose_name='\u751f\u6210\u8bb0\u5f55\u5916\u90e8ID')),
                ('referal_id', models.CharField(blank=True, max_length=32, verbose_name='\u5f15\u7528id')),
            ],
            options={
                'db_table': 'flashsale_account_entry',
                'verbose_name': 'V2/\u5988\u5988\u8d26\u5355\u590d\u5f0f\u8bb0\u5f55',
                'verbose_name_plural': 'V2/\u5988\u5988\u8d26\u5355\u590d\u5f0f\u8bb0\u5f55\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='AccountSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('code', models.CharField(db_index=True, max_length=16, verbose_name='\u79d1\u76ee\u4ee3\u7801')),
                ('name', models.CharField(max_length=32, verbose_name='\u79d1\u76ee\u540d\u79f0')),
                ('parent', models.CharField(max_length=16, verbose_name='\u7236\u7ea7\u79d1\u76ee\u4ee3\u7801')),
            ],
            options={
                'db_table': 'flashsale_account_subject',
                'verbose_name': 'V2/\u5988\u5988\u8d26\u5355\u79d1\u76ee',
                'verbose_name_plural': 'V2/\u5988\u5988\u8d26\u5355\u79d1\u76ee\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='accountentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaolumm.AccountSubject', verbose_name='\u79d1\u76ee'),
        ),
    ]
