# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0080_create_flashsale_xlmm_accountentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteMamaAwardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('customer_id', models.IntegerField(db_index=True, default=0, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('mama_id', models.IntegerField(db_index=True, default=0, verbose_name='\u5988\u5988\u7f16\u53f7')),
                ('status', models.CharField(choices=[('unsend', '\u5f85\u53d1\u653e'), ('send', '\u5df2\u53d1\u653e'), ('cancel', '\u5df2\u53d6\u6d88')], db_index=True, default='unsend', max_length=12, verbose_name='\u72b6\u6001')),
                ('referal_id', models.CharField(blank=True, max_length=32, verbose_name='\u5f15\u7528id')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'flashsale_xlmm_elitemamaawardlog',
                'verbose_name': '\u7cbe\u82f1\u5988\u5988\u5956\u91d1\u8bb0\u5f55',
                'verbose_name_plural': '\u7cbe\u82f1\u5988\u5988\u5956\u91d1\u8bb0\u5f55',
            },
        ),
    ]
