# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0081_create_flashsale_xlmm_elitemamaawardlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninepicadver',
            name='show_qrcode',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a\u4e8c\u7ef4\u7801'),
        ),
    ]
