# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0083_add_balance_to_xiaolucoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaolucoin',
            name='mama_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='\u5988\u5988\u7f16\u53f7'),
        ),
    ]
