# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0084_add_unique_to_xiaolucoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('order_oid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='\u8ba2\u5355OID')),
                ('auto_given_carry', models.BooleanField(default=False, verbose_name='\u81ea\u52a8\u53d1\u4f63')),
                ('exchg_type', models.IntegerField(default=0, verbose_name='\u5151\u6362\u7c7b\u578b')),
                ('has_exchanged', models.BooleanField(default=False, verbose_name='\u5df2\u5151\u6362')),
                ('can_exchg_payment', models.IntegerField(default=0, verbose_name='\u8fd8\u80fd\u5151\u6362\u91d1\u989d\uff08\u5206\uff09')),
            ],
            options={
                'db_table': 'flashsale_xlmm_exchange_order',
                'verbose_name': 'V2/\u8ba2\u5355\u5151\u6362',
                'verbose_name_plural': 'V2/\u8ba2\u5355\u5151\u6362\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='envelop',
            name='platform',
            field=models.CharField(choices=[('wx_pub', '\u5fae\u4fe1\u516c\u4f17\u7ea2\u5305'), ('transfer', '\u5fae\u4fe1\u4f01\u4e1a\u8f6c\u8d26')], db_index=True, max_length=8, verbose_name='\u7ea2\u5305\u53d1\u653e\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='envelop',
            name='subject',
            field=models.CharField(choices=[('cashout', '\u5988\u5988\u4f59\u989d\u63d0\u73b0'), ('ordred', '\u8ba2\u5355\u7ea2\u5305'), ('xlapp', '\u4e2a\u4eba\u96f6\u94b1\u63d0\u73b0'), ('level1', '\u4e00\u7ea7\u63a8\u8350\u4eba'), ('level2', '\u4e8c\u7ea7\u63a8\u8350\u4eba')], db_index=True, max_length=8, verbose_name='\u7ea2\u5305\u4e3b\u9898'),
        ),
        migrations.AlterField(
            model_name='ninepicadver',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ninepicadver',
            name='turns_num',
            field=models.IntegerField(db_index=True, verbose_name='\u8f6e\u6570(\u7b2c\u51e0\u8f6e)'),
        ),
        migrations.AlterField(
            model_name='ordercarry',
            name='carry_type',
            field=models.IntegerField(choices=[(1, '\u5fae\u5546\u57ce\u8ba2\u5355'), (2, 'App\u8ba2\u5355'), (3, '\u4e0b\u5c5e\u8ba2\u5355'), (4, '\u9ad8\u7ea7\u5988\u5988\u4e0b\u5c5e\u8ba2\u5355')], default=1, verbose_name='\u63d0\u6210\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='xiaolucoinlog',
            name='subject',
            field=models.CharField(choices=[('recharge', '\u5145\u503c'), ('consume', '\u6d88\u8d39'), ('refund', '\u9000\u6b3e'), ('gift', '\u8d60\u9001')], db_index=True, max_length=16, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterModelTable(
            name='xlmmeffectscore',
            table='xiaolumm_xlmmeffectscore',
        ),
        migrations.AlterModelTable(
            name='xlmmteameffscore',
            table='xiaolumm_xlmmteameffscore',
        ),
    ]
