# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0086_exchangesaleorder_uni_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesaleorder',
            name='can_exchange',
            field=models.BooleanField(default=True, verbose_name='\u80fd\u5426\u5151\u6362'),
        ),
    ]
