# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0088_add_customer_id_to_envelop'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelop',
            name='fail_msg',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u9519\u8bef\u63d0\u793a'),
        ),
        migrations.AlterField(
            model_name='envelop',
            name='platform',
            field=models.CharField(choices=[('wx_pub', '\u5fae\u4fe1\u516c\u4f17\u7ea2\u5305'), ('transfer', '\u5fae\u4fe1\u4f01\u4e1a\u8f6c\u8d26'), ('sandpay', '\u94f6\u884c\u5361\u8f6c\u8d26')], db_index=True, max_length=8, verbose_name='\u7ea2\u5305\u53d1\u653e\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='weixinpushevent',
            name='tid',
            field=models.IntegerField(default=0, verbose_name='\u6d88\u606f\u6a21\u7248ID-\u4ee3\u7801\u586b\u5199'),
        ),
    ]
