# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaolumm', '0091_add_fail_msg_to_envelop'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelop',
            name='success_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u6210\u529f\u65f6\u95f4'),
        ),
    ]
