# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_category', models.CharField(blank=True, max_length=32, verbose_name='\u81ea\u5b9a\u4e49\u6743\u9650')),
            ],
            options={
                'db_table': 'customize_permissions',
                'verbose_name': '\u81ea\u5b9a\u4e49\u6743\u9650',
                'verbose_name_plural': '\u81ea\u5b9a\u4e49\u6743\u9650\u8868',
                'permissions': [('manage_sale_supplier', '\u7ba1\u7406\u4f9b\u5e94\u5546'), ('manage_sale_category', '\u7ba1\u7406\u7279\u5356/\u9009\u54c1\u5217\u8868'), ('add_product', '\u7ba1\u7406\u6392\u671f'), ('manage_sale_manage_detail', '\u7ba1\u7406\u6392\u671f\u660e\u7ec6'), ('manage_preference_pool', '\u7ba1\u7406\u7279\u5356/\u4ea7\u54c1\u8d44\u6599\u53c2\u6570\u8868'), ('manage_xiaolumama', '\u7ba1\u7406\u5c0f\u9e7f\u5988\u5988'), ('manage_apppushmsg', '\u7ba1\u7406\u6d88\u606f\u63a8\u9001'), ('manage_user_budget', '\u7ba1\u7406\u7279\u5356/APP\u5168\u7ad9\u63a8\u9001'), ('manage_user_coupon', '\u7ba1\u7406\u7279\u5356/\u4f18\u60e0\u5238/\u7528\u6237\u4f18\u60e0\u5238\u8868'), ('manage_transfer_coupondetail', '\u7ba1\u7406\u7279\u5356/\u4f18\u60e0\u5238/\u6d41\u901a\u660e\u7ec6\u8868'), ('manage_ninepicadver', '\u8bbe\u7f6e9\u5f20\u56fe'), ('manage_change_uppermama', '\u66f4\u6539\u4e0a\u7ea7\u5988\u5988'), ('manage_mall_activity', '\u7ba1\u7406\u5546\u57ce\u6d3b\u52a8')],
            },
        ),
    ]
