# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_permissions', '0002_auto_20170308_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermissions',
            options={'permissions': (('manage_sale_supplier', '\u9189\u4e86'),), 'verbose_name': '\u81ea\u5b9a\u4e49\u6743\u9650', 'verbose_name_plural': '\u81ea\u5b9a\u4e49\u6743\u9650\u8868'},
        ),
    ]
