# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tmcnotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tmcuser',
            managers=[
                ('valid_users', django.db.models.manager.Manager()),
            ],
        ),
    ]
