# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-03 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundBuyerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True, verbose_name='\u5173\u8054\u7528\u6237ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('openid', models.CharField(blank=True, max_length=32, null=True, verbose_name='OPENID')),
                ('buyer_name', models.CharField(db_index=True, max_length=16, verbose_name='\u59d3\u540d')),
                ('buy_amount', models.IntegerField(default=0, verbose_name='\u5f53\u524d\u8d2d\u4e70\u91d1\u989d($\u5206)')),
                ('settled_earned_profit', models.IntegerField(default=0, help_text='\u5728\u7528\u6237\u591a\u6b21\u8d2d\u5165\u65f6\u9700\u5c06\u524d\u4e00\u7b14\u6536\u76ca\u7ed3\u7b97\u5b8c\u624d\u80fd\u5904\u7406,\u8fd9\u91cc\u5c31\u662f\u7528\u6237\u65b0\u8d2d\u524d\u672a\u8d4e\u56de\u7d2f\u8ba1\u6536\u76ca', verbose_name='\u65b0\u8d2d\u524d\u7ed3\u7b97\u6536\u76ca($\u5206)')),
                ('annual_yield_rate', models.FloatField(default=0, verbose_name='\u57fa\u91d1\u5e74\u6536\u76ca\u7387(%)')),
                ('total_buy_amount', models.IntegerField(default=0, verbose_name='\u603b\u8d2d\u4e70\u91d1\u989d($\u5206)')),
                ('total_earned_profit', models.IntegerField(default=0, help_text='\u6240\u6709\u5df2\u7ed3\u7b97\u7684\u6536\u76ca\u603b\u548c,\u4e0d\u542b\u5f53\u524d\u672a\u7ed3\u7b97\u7684\u6536\u76ca', verbose_name='\u603b\u7ed3\u7b97\u6536\u76ca($\u5206)')),
                ('total_cashout', models.IntegerField(default=0, verbose_name='\u603b\u8d4e\u56de\u91d1\u989d($\u5206)')),
                ('last_buy_date', models.DateField(default=datetime.datetime.today, verbose_name='\u6700\u540e\u8d2d\u4e70\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
            options={
                'db_table': 'games_fund_buyeraccount',
                'verbose_name': '\u5f18\u5229\u57fa\u91d1\u4e70\u5bb6\u5e10\u53f7',
                'verbose_name_plural': '\u5f18\u5229\u57fa\u91d1\u4e70\u5bb6\u5e10\u53f7\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='FundNotifyMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_data', jsonfield.fields.JSONField(default={}, max_length=5120, verbose_name='\u53d1\u9001\u6d88\u606f\u6570\u636e')),
                ('is_send', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u9001')),
                ('send_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
                ('send_type', models.IntegerField(choices=[(1, '\u6bcf\u5468\u5b9a\u65f6'), (2, '\u624b\u52a8\u67e5\u8be2')], db_index=True, default=2, verbose_name='\u53d1\u9001\u7c7b\u578b')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('fund_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundBuyerAccount', verbose_name='\u5173\u8054\u57fa\u91d1\u7528\u6237\u5e10\u53f7')),
            ],
            options={
                'db_table': 'games_fund_notifymsg',
                'verbose_name': '\u5f18\u5229\u57fa\u91d1\u6d88\u606f\u901a\u77e5',
                'verbose_name_plural': '\u5f18\u5229\u57fa\u91d1\u6d88\u606f\u901a\u77e5\u5217\u8868',
            },
        ),
    ]
