# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundbuyeraccount',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7533\u8bf7\u4e2d'), (1, '\u5df2\u8d2d\u5165'), (2, '\u5df2\u6e05\u9000')], default=0, verbose_name='\u5e10\u53f7\u72b6\u6001'),
        ),
    ]
