# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0049_create_table_flashsale_admanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admanager',
            options={'verbose_name': '\u5e7f\u544a\u7cfb\u7edf', 'verbose_name_plural': '\u5e7f\u544a\u6295\u653e\u7cfb\u7edf'},
        ),
        migrations.AlterField(
            model_name='budgetlog',
            name='budget_log_type',
            field=models.CharField(choices=[('envelop', '\u7ea2\u5305'), ('refund', '\u9000\u6b3e'), ('postage', '\u9000\u6b3e\u8865\u90ae\u8d39'), ('consum', '\u6d88\u8d39'), ('cashout', '\u63d0\u73b0'), ('mmcash', '\u4ee3\u7406\u63d0\u73b0\u81f3\u4f59\u989d'), ('rfan', '\u63a8\u8350\u7c89\u4e1d'), ('subs', '\u5173\u6ce8')], db_index=True, max_length=8, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='districtversion',
            name='hash256',
            field=models.CharField(blank=True, max_length=128, verbose_name='sha1\u503c'),
        ),
        migrations.AlterField(
            model_name='register',
            name='code_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u9a8c\u8bc1\u7801\u751f\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mail_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u9a8c\u8bc1\u7801\u53d1\u9001\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='saleordersynclog',
            name='type',
            field=models.IntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u53d1\u8d27PSI'), (2, '\u8ba2\u8d27PR'), (3, '\u8ba2\u8d27NUM'), (7, '\u5305\u88f9\u5546\u54c1\u5b8c\u6210\u8ba1\u6570'), (5, '\u5165\u5e93\u6709\u591a\u8d27'), (6, '\u5165\u5e93\u6709\u6b21\u54c1'), (4, '\u5305\u88f9\u5546\u54c1\u5b9e\u65f6\u8ba1\u6570'), (8, '\u5907\u8d27\u8ba1\u6570'), (9, '\u6709\u5e93\u5b58\u672a\u5907\u8d27'), (10, '\u8d2d\u7269\u8f66\u8ba2\u5355\u6570'), (11, '\u5f85\u652f\u4ed8\u8ba2\u5355\u6570')], db_index=True, default=0, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='saletrade',
            name='order_type',
            field=models.IntegerField(choices=[(0, '\u7279\u5356\u8ba2\u5355'), (1, '\u9884\u8ba2\u5236'), (3, '\u56e2\u8d2d\u8ba2\u5355'), (2, '\u62bc\u91d1\u8ba2\u5355'), (4, '\u7535\u5b50\u5546\u54c1\u8ba2\u5355')], default=0, verbose_name='\u8ba2\u5355\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='type',
            field=models.IntegerField(choices=[(0, '\u7279\u5356\u8ba2\u5355'), (3, '\u56e2\u8d2d\u8ba2\u5355'), (4, '\u79d2\u6740\u8ba2\u5355'), (5, '\u4f18\u60e0\u5238\u8ba2\u5355')], default=0),
        ),
    ]
