# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0051_useraddress_identification_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlog',
            name='budget_log_type',
            field=models.CharField(choices=[('envelop', '\u7ea2\u5305'), ('refund', '\u9000\u6b3e'), ('postage', '\u9000\u6b3e\u8865\u90ae\u8d39'), ('consum', '\u6d88\u8d39'), ('cashout', '\u63d0\u73b0'), ('mmcash', '\u4ee3\u7406\u63d0\u73b0\u81f3\u4f59\u989d'), ('rfan', '\u63a8\u8350\u7c89\u4e1d'), ('subs', '\u5173\u6ce8'), ('exchg_order', '\u5151\u6362\u8ba2\u5355')], db_index=True, max_length=8, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='product_type',
            field=models.IntegerField(choices=[(0, '\u5546\u54c1'), (1, '\u865a\u62df\u5546\u54c1'), (2, '\u975e\u5356\u54c1')], db_index=True, default=0, verbose_name='\u5546\u54c1\u7c7b\u578b'),
        ),
    ]
