# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0053_budget_chg_alertname'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodshelf',
            name='category',
            field=models.CharField(choices=[('index', '\u9996\u9875'), ('jingpin', '\u7cbe\u54c1\u6c47\u9875\u9762')], default='index', max_length=16, verbose_name='\u6d77\u62a5\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='act_type',
            field=models.CharField(choices=[('webview', '\u666e\u901a\u6d3b\u52a8'), ('atop', '\u5546\u57ceTop10'), ('topic', '\u4e13\u9898\u6d3b\u52a8'), ('brand', '\u54c1\u724c\u4e13\u573a'), ('coupon', '\u4f18\u60e0\u5238\u6d3b\u52a8'), ('mama', '\u5988\u5988\u6d3b\u52a8'), ('jingpin', '\u7cbe\u54c1\u6c47\u6d3b\u52a8')], db_index=True, max_length=8, verbose_name='\u6d3b\u52a8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='is_onsale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7279\u4ef7/\u79d2\u6740(\u7cbe\u54c1\u5238\u5546\u54c1)'),
        ),
    ]
