# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0055_auto_20161213_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbudget',
            options={'verbose_name': '\u7279\u5356/\u7528\u6237\u96f6\u94b1', 'verbose_name_plural': '\u7279\u5356/\u7528\u6237\u96f6\u94b1\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='is_onsale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7279\u4ef7/\u79d2\u6740'),
        ),
        migrations.AlterField(
            model_name='saletrade',
            name='is_boutique',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7cbe\u54c1\u8ba2\u5355'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='item_id',
            field=models.IntegerField(db_index=True, verbose_name='\u5546\u54c1ID'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='sku_id',
            field=models.IntegerField(db_index=True, verbose_name='\u89c4\u683cID'),
        ),
    ]
