# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0056_add_index_to_shoppingcart_item_and_sku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='supplier_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='\u4f9b\u5e94\u5546ID'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.IntegerField(choices=[(1, '\u7528\u6237'), (2, '\u4f9b\u5e94\u5546')], default=1, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='cus_uid',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='\u5ba2\u6237ID'),
        ),
    ]
