# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0057_add_supplierid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('user_id', models.BigIntegerField(db_index=True, default=0, help_text='DjangoUserId', verbose_name='\u7528\u6237id')),
                ('content', models.CharField(max_length=256, verbose_name='\u641c\u7d22\u5185\u5bb9')),
                ('target', models.CharField(choices=[('ModelProduct', '\u7279\u5356\u6b3e\u5f0f')], db_index=True, max_length=16, verbose_name='\u641c\u7d22\u76ee\u6807')),
                ('result_count', models.IntegerField(default=0, verbose_name='\u7ed3\u679c\u6761\u6570')),
                ('status', models.CharField(choices=[('normal', '\u6b63\u5e38'), ('uclear', '\u88ab\u7528\u6237\u6e05\u9664')], db_index=True, default='normal', max_length=8, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'flashsale_user_search_history',
                'verbose_name': '\u7279\u5356\u5546\u57ce/\u7528\u6237\u641c\u7d22\u8868',
                'verbose_name_plural': '\u7279\u5356\u5546\u57ce/\u7528\u6237\u641c\u7d22\u5217\u8868',
            },
        )
    ]
