# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0059_refund_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletrade',
            name='budget_paid',
            field=models.FloatField(default=0.0, verbose_name='\u4f59\u989d\u652f\u4ed8'),
        ),
        migrations.AddField(
            model_name='saletrade',
            name='coin_paid',
            field=models.FloatField(default=0.0, verbose_name='\u5c0f\u9e7f\u5e01\u652f\u4ed8'),
        ),
        migrations.AddField(
            model_name='saletrade',
            name='has_coin_paid',
            field=models.BooleanField(default=False, verbose_name='\u4f7f\u7528\u5c0f\u9e7f\u5e01'),
        ),
        migrations.AlterField(
            model_name='budgetlog',
            name='budget_log_type',
            field=models.CharField(choices=[('refund', '\u9000\u6b3e'), ('postage', '\u9000\u6b3e\u8865\u90ae\u8d39'), ('mmcash', '\u4ee3\u7406\u63d0\u73b0\u81f3\u4f59\u989d'), ('rfan', '\u63a8\u8350\u7c89\u4e1d'), ('subs', '\u5173\u6ce8'), ('rtcoup', '\u9000\u7cbe\u54c1\u5238'), ('envelop', '\u7ea2\u5305'), ('fandian', '\u7cbe\u54c1\u6c47\u8fd4\u70b9'), ('consum', '\u6d88\u8d39'), ('cashout', '\u63d0\u73b0'), ('exchg', '\u5151\u6362\u8ba2\u5355')], db_index=True, max_length=8, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='order_weight',
            field=models.IntegerField(choices=[(200, 200), (199, 199), (198, 198), (197, 197), (196, 196), (195, 195), (194, 194), (193, 193), (192, 192), (191, 191), (190, 190), (189, 189), (188, 188), (187, 187), (186, 186), (185, 185), (184, 184), (183, 183), (182, 182), (181, 181), (180, 180), (179, 179), (178, 178), (177, 177), (176, 176), (175, 175), (174, 174), (173, 173), (172, 172), (171, 171), (170, 170), (169, 169), (168, 168), (167, 167), (166, 166), (165, 165), (164, 164), (163, 163), (162, 162), (161, 161), (160, 160), (159, 159), (158, 158), (157, 157), (156, 156), (155, 155), (154, 154), (153, 153), (152, 152), (151, 151), (150, 150), (149, 149), (148, 148), (147, 147), (146, 146), (145, 145), (144, 144), (143, 143), (142, 142), (141, 141), (140, 140), (139, 139), (138, 138), (137, 137), (136, 136), (135, 135), (134, 134), (133, 133), (132, 132), (131, 131), (130, 130), (129, 129), (128, 128), (127, 127), (126, 126), (125, 125), (124, 124), (123, 123), (122, 122), (121, 121), (120, 120), (119, 119), (118, 118), (117, 117), (116, 116), (115, 115), (114, 114), (113, 113), (112, 112), (111, 111), (110, 110), (109, 109), (108, 108), (107, 107), (106, 106), (105, 105), (104, 104), (103, 103), (102, 102), (101, 101), (100, 100), (99, 99), (98, 98), (97, 97), (96, 96), (95, 95), (94, 94), (93, 93), (92, 92), (91, 91), (90, 90), (89, 89), (88, 88), (87, 87), (86, 86), (85, 85), (84, 84), (83, 83), (82, 82), (81, 81), (80, 80), (79, 79), (78, 78), (77, 77), (76, 76), (75, 75), (74, 74), (73, 73), (72, 72), (71, 71), (70, 70), (69, 69), (68, 68), (67, 67), (66, 66), (65, 65), (64, 64), (63, 63), (62, 62), (61, 61), (60, 60), (59, 59), (58, 58), (57, 57), (56, 56), (55, 55), (54, 54), (53, 53), (52, 52), (51, 51), (50, 50), (49, 49), (48, 48), (47, 47), (46, 46), (45, 45), (44, 44), (43, 43), (42, 42), (41, 41), (40, 40), (39, 39), (38, 38), (37, 37), (36, 36), (35, 35), (34, 34), (33, 33), (32, 32), (31, 31), (30, 30), (29, 29), (28, 28), (27, 27), (26, 26), (25, 25), (24, 24), (23, 23), (22, 22), (21, 21), (20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], db_index=True, default=8, verbose_name='\u6743\u503c'),
        ),
        migrations.AlterField(
            model_name='saletrade',
            name='channel',
            field=models.CharField(blank=True, choices=[('budget', '\u5c0f\u9e7f\u94b1\u5305'), ('wallet', '\u5988\u5988\u94b1\u5305'), ('wx', '\u5fae\u4fe1APP'), ('weapp', '\u5c0f\u7a0b\u5e8f\u652f\u4ed8'), ('alipay', '\u652f\u4ed8\u5b9dAPP'), ('wx_pub', '\u5fae\u4fe1WAP'), ('alipay_wap', '\u652f\u4ed8\u5b9dWAP'), ('upmp_wap', '\u94f6\u8054'), ('applepay_upacp', 'ApplePay')], db_index=True, max_length=16, verbose_name='\u4ed8\u6b3e\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='type',
            field=models.IntegerField(choices=[(0, '\u7279\u5356\u8ba2\u5355'), (3, '\u56e2\u8d2d\u8ba2\u5355'), (4, '\u79d2\u6740\u8ba2\u5355'), (5, '\u4f18\u60e0\u5238\u8ba2\u5355'), (6, '\u5238\u5546\u54c1\u8ba2\u5355')], default=0),
        ),
    ]
