# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0060_add_budget_paid_and_coin_paid_and_has_coin_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, null=True, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='budgetlog',
            name='budget_log_type',
            field=models.CharField(choices=[('refund', '\u9000\u6b3e'), ('postage', '\u9000\u6b3e\u8865\u90ae\u8d39'), ('mmcash', '\u4ee3\u7406\u63d0\u73b0\u81f3\u4f59\u989d'), ('rfan', '\u63a8\u8350\u7c89\u4e1d'), ('subs', '\u5173\u6ce8'), ('rtcoup', '\u9000\u7cbe\u54c1\u5238'), ('envelop', '\u7ea2\u5305'), ('fandian', '\u7cbe\u54c1\u6c47\u8fd4\u70b9'), ('click', '\u70b9\u51fb\u6536\u76ca'), ('order', '\u8ba2\u5355\u6536\u76ca'), ('award', '\u5956\u91d1\u6536\u76ca'), ('exchg', '\u5151\u6362\u8ba2\u5355'), ('consum', '\u6d88\u8d39'), ('cashout', '\u63d0\u73b0'), ('mmconsum', '\u5988\u5988\u6d88\u8d39'), ('rtexchg', '\u53d6\u6d88\u5151\u6362')], db_index=True, max_length=8, verbose_name='\u8bb0\u5f55\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='salerefund',
            name='sku_id',
            field=models.BigIntegerField(db_index=True, default=0, null=True, verbose_name='\u89c4\u683cID'),
        ),
    ]
