# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0065_create_flashsale_openapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='title_imgs',
            field=jsonfield.fields.JSONField(default=dict, help_text='\u591a\u8272\u5219\u591a\u56fe\uff0c\u5355\u8272\u5219\u5355\u56fe', max_length=5000, verbose_name='\u4e3b\u56fe'),
        ),
    ]
