# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0066_modelproduct_title_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='detail_first_img',
            field=models.TextField(blank=True, verbose_name='\u8be6\u60c5\u9996\u56fe'),
        )
    ]
