# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0067_model_product_first_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('brand_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='\u54c1\u724c\u540d\u79f0(\u56fd\u5185)')),
                ('brand_desc', models.TextField(blank=True, null=True, verbose_name='\u54c1\u724c\u7b80\u4ecb')),
                ('extras', jsonfield.fields.JSONField(blank=True, default={}, max_length=1024, verbose_name='\u9644\u52a0\u4fe1\u606f')),
            ],
            options={
                'db_table': 'flashsale_product_brand',
                'verbose_name': '\u7279\u5356/\u5546\u54c1\u54c1\u724c',
                'verbose_name_plural': '\u7279\u5356/\u5546\u54c1\u54c1\u724c',
            },
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='act_type',
            field=models.CharField(choices=[('webview', '\u666e\u901a\u6d3b\u52a8'), ('atop', '\u5546\u57ceTop10'), ('topic', '\u4e13\u9898\u6d3b\u52a8'), ('brand', '\u54c1\u724c\u4e13\u573a'), ('coupon', '\u4f18\u60e0\u5238\u6d3b\u52a8'), ('mama', '\u5988\u5988\u6d3b\u52a8'), ('jingpin', '\u7cbe\u54c1\u6c47\u6d3b\u52a8'), ('focus', '\u6bcf\u65e5\u7126\u70b9')], db_index=True, max_length=8, verbose_name='\u6d3b\u52a8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='content_imgs',
            field=models.TextField(blank=True, help_text='\u591a\u8272\u5219\u591a\u56fe\uff0c\u5355\u8272\u5219\u5355\u56fe', verbose_name='\u5185\u5bb9\u7167(\u591a\u5f20\u8bf7\u6362\u884c)'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='product_type',
            field=models.IntegerField(choices=[(0, '\u5546\u54c1'), (1, '\u865a\u62df\u5546\u54c1'), (2, '\u5305\u6750\u8f85\u6599')], db_index=True, default=0, verbose_name='\u5546\u54c1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='type',
            field=models.IntegerField(choices=[(0, '\u7279\u5356\u8ba2\u5355'), (3, '\u56e2\u8d2d\u8ba2\u5355'), (4, '\u79d2\u6740\u8ba2\u5355'), (5, '\u7cbe\u54c1\u6c47\u8ba2\u5355'), (6, '\u5238\u5546\u54c1\u8ba2\u5355')], default=0),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.ProductBrand', verbose_name='\u54c1\u724c'),
        ),
    ]
