# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0068_add_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlog',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='\u53d8\u52a8\u540e\u91d1\u989d(\u5206)'),
        ),
    ]
