# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0070_add_index_to_activity_order_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='charger',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
    ]
