# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0071_modelproduct_add_charger'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='is_outside',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u6d77\u5916\u76f4\u90ae'),
        ),
    ]
