# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixingroup', '0008_liangxifans_add_gifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfans',
            name='union_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u7528\u6237\u5fae\u4fe1unionid'),
        ),
        migrations.AlterField(
            model_name='groupfans',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5173\u8054\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='xiaoluadministrator',
            name='user_id',
            field=models.IntegerField(verbose_name='\u540e\u53f0\u7528\u6237id'),
        ),
        migrations.AlterField(
            model_name='xiaoluadministrator',
            name='username',
            field=models.CharField(max_length=64, verbose_name='\u7ba1\u7406\u5458\u540e\u53f0\u7528\u6237\u540d'),
        ),
    ]
