# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixingroup', '0009_auto_20161118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaoluadministrator',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u7279\u6b8a\u8d26\u53f7\uff08\u516c\u53f8\u804c\u5458\uff09'),
        ),
        migrations.AddField(
            model_name='xiaoluadministrator',
            name='mama_id',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='\u5988\u5988\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='xiaoluadministrator',
            name='nick',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='\u4e8c\u7ef4\u7801\u5f52\u5c5e\u4eba\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='xiaoluadministrator',
            name='user_id',
            field=models.IntegerField(verbose_name='\u7ba1\u7406\u5458\u7528\u6237id'),
        ),
        migrations.AlterField(
            model_name='xiaoluadministrator',
            name='username',
            field=models.CharField(max_length=64, verbose_name='\u7ba1\u7406\u5458\u7528\u6237\u540d'),
        ),
    ]
